// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class DtColumnComponentAlignType extends BaseType<string> {}

applyValidValues(DtColumnComponentAlignType, [
  "left",
  "center",
  "right",
]);
