// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class MatCardAppearanceType extends BaseType<string> {}

applyValidValues(MatCardAppearanceType, [
  "outlined",
  "raised",
]);
