// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class MatAccordionDisplayModeType extends BaseType<string> {}

applyValidValues(MatAccordionDisplayModeType, [
  "default",
  "flat",
]);
