// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class MatTabGroupHeaderPositionPosition extends BaseType<string> {}

applyValidValues(MatTabGroupHeaderPositionPosition, [
  "above",
  "below",
]);
