// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class MatDialogCloseTypeType extends BaseType<string> {}

applyValidValues(MatDialogCloseTypeType, [
  "submit",
  "button",
  "reset",
]);
