// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class MatFormFieldThemePalette extends BaseType<string> {}

applyValidValues(MatFormFieldThemePalette, [
  "primary",
  "accent",
  "warn",
]);
