// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class MatCheckboxLabelPositionPosition extends BaseType<string> {}

applyValidValues(MatCheckboxLabelPositionPosition, [
  "before",
  "after",
]);
