// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class RouterLinkQueryParamsHandlingType extends BaseType<string> {}

applyValidValues(RouterLinkQueryParamsHandlingType, [
  "",
  "merge",
  "preserve",
  "replace",
]);
