// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkRecycleRows } from "@angular/cdk/table";

/**
 * Enables the recycle view repeater strategy, which reduces rendering latency. Not compatible with
tables that animate rows.
 */
@directiveInterface({ selector: "cdk-table[recycleRows],table[cdk-table][recycleRows]" })
export class CdkRecycleRowsDirectiveInterface {
}
