// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { CdkRow } from "@angular/cdk/table";

/**
 * Data row template container that contains the cell outlet. Adds the right class and role.
 */
@componentInterface({ selector: "cdk-row,tr[cdk-row]", acceptsChildren: true })
export class CdkRowComponentInterface {
}
