// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { CdkTreeNode } from "@angular/cdk/tree";

/**
 * Tree node for CdkTree. It contains the data in the tree node.
 */
@componentInterface({ selector: "cdk-tree-node" })
export class CdkTreeNodeComponentInterface {
  role!: any;
  isExpandable!: any;
  isExpanded!: any;
  isDisabled!: any;
  cdkTreeNodeTypeaheadLabel!: any;
  @output() activation!: any;
  @output() expandedChange!: any;
}
