// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { CdkNestedTreeNode } from "@angular/cdk/tree";

/**
 * Nested node is a child of `<cdk-tree>`. It works with nested tree.
By using `cdk-nested-tree-node` component in tree node template, children of the parent node will
be added in the `cdkTreeNodeOutlet` in tree node template.
The children of node will be automatically added to `cdkTreeNodeOutlet`.
 */
@componentInterface({ selector: "cdk-nested-tree-node" })
export class CdkNestedTreeNodeComponentInterface {
}
