// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { CdkTable } from "@angular/cdk/table";

/**
 * A data table that can render a header row, data rows, and a footer row.
Uses the dataSource input to determine the data to be rendered. The data can be provided either
as a data array, an Observable stream that emits the data array to render, or a DataSource with a
connect function that will return an Observable stream that emits the data array to render.
 */
@componentInterface({ selector: "cdk-table,table[cdk-table]", acceptsChildren: true })
export class CdkTableComponentInterface {
  trackBy!: any;
  dataSource!: any;
  multiTemplateDataRows!: any;
  fixedLayout!: any;
  @output() contentChanged!: any;
}
