// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkVirtualScrollableElement } from "@angular/cdk/scrolling";

/**
 * Provides a virtual scrollable for the element it is attached to.
 */
@directiveInterface({ selector: "[cdkVirtualScrollingElement]" })
export class CdkVirtualScrollableElementDirectiveInterface {
}
