// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkMenuItemRadio } from "@angular/cdk/menu";

/**
 * A directive providing behavior for the "menuitemradio" ARIA role, which behaves similarly to
a conventional radio-button. Any sibling `CdkMenuItemRadio` instances within the same `CdkMenu`
or `CdkMenuGroup` comprise a radio group with unique selection enforced.
 */
@directiveInterface({ selector: "[cdkMenuItemRadio]" })
export class CdkMenuItemRadioDirectiveInterface {
}
