// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkMenuItemCheckbox } from "@angular/cdk/menu";

/**
 * A directive providing behavior for the "menuitemcheckbox" ARIA role, which behaves similarly to a
conventional checkbox.
 */
@directiveInterface({ selector: "[cdkMenuItemCheckbox]" })
export class CdkMenuItemCheckboxDirectiveInterface {
}
