// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { CdkStepper } from "@angular/cdk/stepper";

@directiveInterface({ selector: "[cdkStepper]" })
export class CdkStepperDirectiveInterface {
  linear!: any;
  selectedIndex!: any;
  selected!: any;
  orientation!: any;
  @output() selectionChange!: any;
  @output() selectedIndexChange!: any;
}
