// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkHeaderRowDef } from "@angular/cdk/table";

/**
 * Header row definition for the CDK table.
Captures the header row's template and other header properties such as the columns to display.
 */
@directiveInterface({ selector: "[cdkHeaderRowDef]" })
export class CdkHeaderRowDefDirectiveInterface {
  cdkHeaderRowDef!: any;
  cdkHeaderRowDefSticky!: any;
}
