// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkTreeNodeOutlet } from "@angular/cdk/tree";

/**
 * Outlet for nested CdkNode. Put `[cdkTreeNodeOutlet]` on a tag to place children dataNodes
inside the outlet.
 */
@directiveInterface({ selector: "[cdkTreeNodeOutlet]" })
export class CdkTreeNodeOutletDirectiveInterface {
}
