// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkFooterCell } from "@angular/cdk/table";

/**
 * Footer cell template container that adds the right classes and role.
 */
@directiveInterface({ selector: "cdk-footer-cell,td[cdk-footer-cell]" })
export class CdkFooterCellDirectiveInterface {
}
