// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkColumnDef } from "@angular/cdk/table";

/**
 * Column definition for the CDK table.
Defines a set of cells available for a table column.
 */
@directiveInterface({ selector: "[cdkColumnDef]" })
export class CdkColumnDefDirectiveInterface {
  cdkColumnDef!: any;
  sticky!: any;
  stickyEnd!: any;
}
