// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkDragPreview } from "@angular/cdk/drag-drop";

/**
 * Element that will be used as a template for the preview
of a CdkDrag when it is being dragged.
 */
@directiveInterface({ selector: "ng-template[cdkDragPreview]" })
export class CdkDragPreviewDirectiveInterface {
  data!: any;
  matchSize!: any;
}
