// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkOverlayOrigin } from "@angular/cdk/overlay";

/**
 * Directive applied to an element to make it usable as an origin for an Overlay using a
ConnectedPositionStrategy.
 */
@directiveInterface({ selector: "[cdk-overlay-origin],[cdkOverlayOrigin],[overlay-origin]" })
export class CdkOverlayOriginDirectiveInterface {
}
