// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { CdkDropList } from "@angular/cdk/drag-drop";

/**
 * Container that wraps a set of draggable items.
 */
@componentInterface({ selector: "[cdkDropList],cdk-drop-list" })
export class CdkDropListComponentInterface {
  cdkDropListConnectedTo!: any;
  cdkDropListData!: any;
  cdkDropListOrientation!: any;
  id!: any;
  cdkDropListLockAxis!: any;
  cdkDropListDisabled!: any;
  cdkDropListSortingDisabled!: any;
  cdkDropListEnterPredicate!: any;
  cdkDropListSortPredicate!: any;
  cdkDropListAutoScrollDisabled!: any;
  cdkDropListAutoScrollStep!: any;
  cdkDropListElementContainer!: any;
  @output() cdkDropListDropped!: any;
  @output() cdkDropListEntered!: any;
  @output() cdkDropListExited!: any;
  @output() cdkDropListSorted!: any;
}
