// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkTargetMenuAim } from "@angular/cdk/menu";

/**
 * CdkTargetMenuAim is a provider for the TargetMenuAim service. It can be added to an
element with either the `cdkMenu` or `cdkMenuBar` directive and child menu items.
 */
@directiveInterface({ selector: "[cdkTargetMenuAim]" })
export class CdkTargetMenuAimDirectiveInterface {
}
