// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { CdkAccordionItem } from "@angular/cdk/accordion";

/**
 * A basic directive expected to be extended and decorated as a component.  Sets up all
events and attributes needed to be managed by a CdkAccordion parent.
 */
@componentInterface({ selector: "[cdkAccordionItem],cdk-accordion-item" })
export class CdkAccordionItemComponentInterface {
  expanded!: any;
  disabled!: any;
  @output() closed!: any;
  @output() opened!: any;
  @output() destroyed!: any;
  @output() expandedChange!: any;
}
