// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkCellDef } from "@angular/cdk/table";

/**
 * Cell definition for a CDK table.
Captures the template of a column's data row cell as well as cell-specific properties.
 */
@directiveInterface({ selector: "[cdkCellDef]" })
export class CdkCellDefDirectiveInterface {
}
