// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkTextareaAutosize } from "@angular/cdk/text-field";

/**
 * Directive to automatically resize a textarea to fit its content.
 */
@directiveInterface({ selector: "textarea[cdkTextareaAutosize]" })
export class CdkTextareaAutosizeDirectiveInterface {
  cdkAutosizeMinRows!: any;
  cdkAutosizeMaxRows!: any;
  cdkTextareaAutosize!: any;
  placeholder!: any;
}
