// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { CdkPortalOutlet } from "@angular/cdk/portal";

/**
 * Directive version of a PortalOutlet. Because the directive *is* a PortalOutlet, portals can be
directly attached to it, enabling declarative use.

Usage:
`<ng-template [cdkPortalOutlet]="greeting"></ng-template>`
 */
@directiveInterface({ selector: "[cdkPortalOutlet]" })
export class CdkPortalOutletDirectiveInterface {
  cdkPortalOutlet!: any;
  @output() attached!: any;
}
