// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkFooterCellDef } from "@angular/cdk/table";

/**
 * Footer cell definition for a CDK table.
Captures the template of a column's footer cell and as well as cell-specific properties.
 */
@directiveInterface({ selector: "[cdkFooterCellDef]" })
export class CdkFooterCellDefDirectiveInterface {
}
