// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkFooterRow } from "@angular/cdk/table";

/**
 * Footer template container that contains the cell outlet. Adds the right class and role.
 */
@directiveInterface({ selector: "cdk-footer-row,tr[cdk-footer-row]" })
export class CdkFooterRowDirectiveInterface {
}
