// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { CdkStep } from "@angular/cdk/stepper";

@componentInterface({ selector: "cdk-step", acceptsChildren: true })
export class CdkStepComponentInterface {
  stepControl!: any;
  label!: any;
  errorMessage!: any;
  "aria-label"!: any;
  "aria-labelledby"!: any;
  state!: any;
  editable!: any;
  optional!: any;
  completed!: any;
  hasError!: any;
  @output() interacted!: any;
}
