// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkStepperPrevious } from "@angular/cdk/stepper";

/**
 * Button that moves to the previous step in a stepper workflow.
 */
@directiveInterface({ selector: "button[cdkStepperPrevious]" })
export class CdkStepperPreviousDirectiveInterface {
  type!: any;
}
