// Generated by @apexdesigner/extract-interfaces
import { pipeInterface } from "@apexdesigner/dsl/pipe-interface";
import { DatePipe } from "@angular/common";

@pipeInterface({ selector: "date" })
export class DatePipePipeInterface {}
