// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { Dir } from "@angular/cdk/bidi";

/**
 * Directive to listen for changes of direction of part of the DOM.

Provides itself as Directionality such that descendant directives only need to ever inject
Directionality to get the closest direction.
 */
@directiveInterface({ selector: "[dir]" })
export class DirDirectiveInterface {
  dir!: any;
  @output() dirChange!: any;
}
