// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { DtEmptyStateComponent } from "@apexdesigner/declarative-tables";

/**
 * Container for custom empty state content displayed when the table has no data.

This component is shown when the parent dt-table's dataSource is an empty array.
Content projected into this component will be displayed in place of the empty table.
 */
@componentInterface({ selector: "dt-empty-state", acceptsChildren: true })
export class DtEmptyStateComponentComponentInterface {
}
