// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { FlexRowComponent } from "@apexdesigner/flex-layout";

/**
 * A flex container component that arranges its children in a horizontal row.
 */
@componentInterface({ selector: "flex-row", acceptsChildren: true })
export class FlexRowComponentComponentInterface {
  gap!: any;
  alignCenter!: any;
}
