// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { GrowDirective } from "@apexdesigner/flex-layout";

/**
 * A directive that makes an element grow to fill available space in a flex container.

Sets the element's flex property and manages overflow behavior. When combined with
the scroll directive, it preserves vertical scrolling while hiding horizontal overflow.
 */
@directiveInterface({ selector: "[grow]" })
export class GrowDirectiveDirectiveInterface {
  grow!: any;
}
