// Generated by @apexdesigner/extract-interfaces
import { pipeInterface } from "@apexdesigner/dsl/pipe-interface";
import { KeyValuePipe } from "@angular/common";

@pipeInterface({ selector: "keyvalue" })
export class KeyValuePipePipeInterface {}
