// Generated by @apexdesigner/extract-interfaces
import { pipeInterface } from "@apexdesigner/dsl/pipe-interface";
import { LowerCasePipe } from "@angular/common";

/**
 * Transforms text to all lower case.
 */
@pipeInterface({ selector: "lowercase" })
export class LowerCasePipePipeInterface {}
