// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatChipAvatar } from "@angular/material/chips";

/**
 * Avatar image within a chip.
 */
@directiveInterface({ selector: "[matChipAvatar],mat-chip-avatar" })
export class MatChipAvatarDirectiveInterface {
}
