// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatHeaderCell } from "@angular/material/table";

/**
 * Header cell template container that adds the right classes and role.
 */
@directiveInterface({ selector: "mat-header-cell,th[mat-header-cell]" })
export class MatHeaderCellDirectiveInterface {
}
