// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatListItemMeta } from "@angular/material/list";

/**
 * Directive matching an optional meta section for list items.

List items can reserve space at the end of an item to display a control,
button or additional text content.
 */
@directiveInterface({ selector: "[matListItemMeta]" })
export class MatListItemMetaDirectiveInterface {
}
