// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatHeaderRowDef } from "@angular/material/table";

/**
 * Header row definition for the mat-table.
Captures the header row's template and other header properties such as the columns to display.
 */
@directiveInterface({ selector: "[matHeaderRowDef]" })
export class MatHeaderRowDefDirectiveInterface {
  matHeaderRowDef!: any;
  matHeaderRowDefSticky!: any;
}
