// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { MatEndDate } from "@angular/material/datepicker";

/**
 * Input for entering the end date in a `mat-date-range-input`.
 */
@directiveInterface({ selector: "input[matEndDate]" })
export class MatEndDateDirectiveInterface {
  @output() dateChange!: any;
  @output() dateInput!: any;
}
