// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatFooterCellDef } from "@angular/material/table";

/**
 * Footer cell definition for the mat-table.
Captures the template of a column's footer cell and as well as cell-specific properties.
 */
@directiveInterface({ selector: "[matFooterCellDef]" })
export class MatFooterCellDefDirectiveInterface {
}
