// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatChipTrailingIcon } from "@angular/material/chips";

/**
 * Non-interactive trailing icon in a chip.
 */
@directiveInterface({ selector: "[matChipTrailingIcon],mat-chip-trailing-icon" })
export class MatChipTrailingIconDirectiveInterface {
}
