// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatLabel } from "@angular/material/input";

/**
 * The floating label for a `mat-form-field`.
 */
@componentInterface({ selector: "mat-label" })
export class MatLabelComponentInterface {
}
