// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatRadioButton } from "@angular/material/radio";

@componentInterface({ selector: "mat-radio-button", acceptsChildren: true })
export class MatRadioButtonComponentInterface {
  id!: any;
  name!: any;
  "aria-label"!: any;
  "aria-labelledby"!: any;
  "aria-describedby"!: any;
  disableRipple!: any;
  tabIndex!: any;
  checked!: any;
  value!: any;
  labelPosition!: any;
  disabled!: any;
  required!: any;
  color!: any;
  disabledInteractive!: any;
  @output() change!: any;
}
