// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatStepLabel } from "@angular/material/stepper";

@directiveInterface({ selector: "[matStepLabel]" })
export class MatStepLabelDirectiveInterface {
}
