// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatDateRangeInput } from "@angular/material/datepicker";

@componentInterface({ selector: "mat-date-range-input", acceptsChildren: true })
export class MatDateRangeInputComponentInterface {
  rangePicker!: any;
  required!: any;
  dateFilter!: any;
  min!: any;
  max!: any;
  disabled!: any;
  separator!: any;
  comparisonStart!: any;
  comparisonEnd!: any;
}
