// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatDatepickerToggleIcon } from "@angular/material/datepicker";

/**
 * Can be used to override the icon of a `matDatepickerToggle`.
 */
@directiveInterface({ selector: "[matDatepickerToggleIcon]" })
export class MatDatepickerToggleIconDirectiveInterface {
}
