// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatButtonToggleGroup } from "@angular/material/button-toggle";

/**
 * Exclusive selection button toggle group that behaves like a radio-button group.
 */
@componentInterface({ selector: "mat-button-toggle-group" })
export class MatButtonToggleGroupComponentInterface {
  appearance!: any;
  name!: any;
  vertical!: any;
  value!: any;
  multiple!: any;
  disabled!: any;
  disabledInteractive!: any;
  hideSingleSelectionIndicator!: any;
  hideMultipleSelectionIndicator!: any;
  @output() valueChange!: any;
  @output() change!: any;
}
