// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatDrawer } from "@angular/material/sidenav";

/**
 * This component corresponds to a drawer that can be opened on the drawer container.
 */
@componentInterface({ selector: "mat-drawer", acceptsChildren: true })
export class MatDrawerComponentInterface {
  position!: any;
  mode!: any;
  disableClose!: any;
  autoFocus!: any;
  opened!: any;
  @output() openedChange!: any;
  @output() openedStart!: any;
  @output() closed!: any;
  @output() closedStart!: any;
  @output() positionChanged!: any;
}
