// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatExpansionPanelTitle } from "@angular/material/expansion";

/**
 * Title element of a `<mat-expansion-panel-header>`.
 */
@componentInterface({ selector: "mat-panel-title" })
export class MatExpansionPanelTitleComponentInterface {
}
