// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatListOption } from "@angular/material/list";

@componentInterface({ selector: "mat-list-option", acceptsChildren: true })
export class MatListOptionComponentInterface {
  togglePosition!: any;
  checkboxPosition!: any;
  color!: any;
  value!: any;
  selected!: any;
  @output() selectedChange!: any;
}
