// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatButton } from "@angular/material/button";

/**
 * Material Design button component. Users interact with a button to perform an action.
See https://material.io/components/buttons

The `MatButton` class applies to native button elements and captures the appearances for
"text button", "outlined button", and "contained button" per the Material Design
specification. `MatButton` additionally captures an additional "flat" appearance, which matches
"contained" but without elevation.
 */
@directiveInterface({ selector: "button[mat-button],button[mat-flat-button],button[mat-raised-button],button[mat-stroked-button]" })
export class MatButtonDirectiveInterface {
}
