// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatOptgroup } from "@angular/material/core";

/**
 * Component that is used to group instances of `mat-option`.
 */
@componentInterface({ selector: "mat-optgroup", acceptsChildren: true })
export class MatOptgroupComponentInterface {
  label!: any;
  disabled!: any;
}
