// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatDatepickerInput } from "@angular/material/datepicker";

/**
 * Directive used to connect an input to a MatDatepicker.
 */
@directiveInterface({ selector: "input[matDatepicker]" })
export class MatDatepickerInputDirectiveInterface {
  matDatepicker!: any;
  min!: any;
  max!: any;
  matDatepickerFilter!: any;
}
