// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatSelect } from "@angular/material/select";

@componentInterface({ selector: "mat-select", acceptsChildren: true })
export class MatSelectComponentInterface {
  "aria-describedby"!: any;
  panelClass!: any;
  disabled!: any;
  disableRipple!: any;
  tabIndex!: any;
  hideSingleSelectionIndicator!: any;
  placeholder!: any;
  required!: any;
  multiple!: any;
  disableOptionCentering!: any;
  compareWith!: any;
  value!: any;
  "aria-label"!: any;
  "aria-labelledby"!: any;
  errorStateMatcher!: any;
  typeaheadDebounceInterval!: any;
  sortComparator!: any;
  id!: any;
  panelWidth!: any;
  canSelectNullableOptions!: any;
  @output() openedChange!: any;
  @output() opened!: any;
  @output() closed!: any;
  @output() selectionChange!: any;
  @output() valueChange!: any;
}
