// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatPaginator } from "@angular/material/paginator";

/**
 * Component to provide navigation between paged information. Displays the size of the current
page, user-selectable options to change that size, what items are being shown, and
navigational button to go to the previous or next page.
 */
@componentInterface({ selector: "mat-paginator", acceptsChildren: true })
export class MatPaginatorComponentInterface {
  color!: any;
  pageIndex!: any;
  length!: any;
  pageSize!: any;
  pageSizeOptions!: any;
  hidePageSize!: any;
  showFirstLastButtons!: any;
  selectConfig!: any;
  disabled!: any;
  @output() page!: any;
}
