// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatCardHeader } from "@angular/material/card";

/**
 * Header region of a card, intended for use within `<mat-card>`. This header captures
a card title, subtitle, and avatar.  This component is an optional convenience for use with
other convenience elements, such as `<mat-card-footer>`; any custom header block element may be
used in its place.

MatCardHeader provides no behaviors, instead serving as a purely visual treatment.
 */
@componentInterface({ selector: "mat-card-header", acceptsChildren: true })
export class MatCardHeaderComponentInterface {
}
