// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatTable } from "@angular/material/table";

@directiveInterface({ selector: "mat-table,table[mat-table]" })
export class MatTableDirectiveInterface {
}
