// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatStepperPrevious } from "@angular/material/stepper";

/**
 * Button that moves to the previous step in a stepper workflow.
 */
@directiveInterface({ selector: "button[matStepperPrevious]" })
export class MatStepperPreviousDirectiveInterface {
}
