// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatDialogTitle } from "@angular/material/dialog";

/**
 * Title of a dialog element. Stays fixed to the top of the dialog when scrolling.
 */
@directiveInterface({ selector: "[mat-dialog-title],[matDialogTitle]" })
export class MatDialogTitleDirectiveInterface {
  id!: any;
}
