// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { MatMenuTrigger } from "@angular/material/menu";

/**
 * Directive applied to an element that should trigger a `mat-menu`.
 */
@directiveInterface({ selector: "[mat-menu-trigger-for],[matMenuTriggerFor]" })
export class MatMenuTriggerDirectiveInterface {
  "mat-menu-trigger-for"!: any;
  matMenuTriggerFor!: any;
  matMenuTriggerData!: any;
  matMenuTriggerRestoreFocus!: any;
  @output() menuOpened!: any;
  @output() onMenuOpen!: any;
  @output() menuClosed!: any;
  @output() onMenuClose!: any;
}
