// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { MatChipOption } from "@angular/material/chips";

/**
 * An extension of the MatChip component that supports chip selection. Used with MatChipListbox.

Unlike other chips, the user can focus on disabled chip options inside a MatChipListbox. The
user cannot click disabled chips.
 */
@directiveInterface({ selector: "[mat-basic-chip-option],[mat-chip-option],mat-basic-chip-option,mat-chip-option" })
export class MatChipOptionDirectiveInterface {
  selectable!: any;
  selected!: any;
  @output() selectionChange!: any;
}
