// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatSlideToggle } from "@angular/material/slide-toggle";

@componentInterface({ selector: "mat-slide-toggle", acceptsChildren: true })
export class MatSlideToggleComponentInterface {
  name!: any;
  id!: any;
  labelPosition!: any;
  "aria-label"!: any;
  "aria-labelledby"!: any;
  "aria-describedby"!: any;
  required!: any;
  color!: any;
  disabled!: any;
  disableRipple!: any;
  tabIndex!: any;
  checked!: any;
  hideIcon!: any;
  disabledInteractive!: any;
  @output() change!: any;
  @output() toggleChange!: any;
}
