// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatError } from "@angular/material/input";

/**
 * Single error message to be shown underneath the form-field.
 */
@directiveInterface({ selector: "[matError],mat-error" })
export class MatErrorDirectiveInterface {
  id!: any;
}
