// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatDialogContent } from "@angular/material/dialog";

/**
 * Scrollable content container of a dialog.
 */
@directiveInterface({ selector: "[mat-dialog-content],[matDialogContent],mat-dialog-content" })
export class MatDialogContentDirectiveInterface {
}
