// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatExpansionPanelContent } from "@angular/material/expansion";

/**
 * Expansion panel content that will be rendered lazily
after the panel is opened for the first time.
 */
@directiveInterface({ selector: "ng-template[matExpansionPanelContent]" })
export class MatExpansionPanelContentDirectiveInterface {
}
