// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatColumnDef } from "@angular/material/table";

/**
 * Column definition for the mat-table.
Defines a set of cells available for a table column.
 */
@directiveInterface({ selector: "[matColumnDef]" })
export class MatColumnDefDirectiveInterface {
  matColumnDef!: any;
}
