// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatChip } from "@angular/material/chips";

/**
 * Material design styled Chip base component. Used inside the MatChipSet component.

Extended by MatChipOption and MatChipRow for different interaction patterns.
 */
@componentInterface({ selector: "[mat-basic-chip],[mat-chip],mat-basic-chip,mat-chip", acceptsChildren: true })
export class MatChipComponentInterface {
  role!: any;
  id!: any;
  "aria-label"!: any;
  "aria-description"!: any;
  value!: any;
  color!: any;
  removable!: any;
  highlighted!: any;
  disableRipple!: any;
  disabled!: any;
  @output() removed!: any;
  @output() destroyed!: any;
}
