// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { MatTimepickerInput } from "@angular/material/timepicker";

/**
 * Input that can be used to enter time and connect to a `mat-timepicker`.
 */
@directiveInterface({ selector: "input[matTimepicker]" })
export class MatTimepickerInputDirectiveInterface {
  value!: any;
  matTimepicker!: any;
  matTimepickerMin!: any;
  matTimepickerMax!: any;
  disabled!: any;
  @output() valueChange!: any;
}
