// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatHeaderCell } from "@angular/material/table";

/**
 * Header cell template container that adds the right classes and role.
 */
@componentInterface({ selector: "mat-header-cell,th[mat-header-cell]" })
export class MatHeaderCellComponentInterface {
}
