// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatHint } from "@angular/material/input";

/**
 * Hint text to be shown underneath the form field control.
 */
@componentInterface({ selector: "mat-hint" })
export class MatHintComponentInterface {
  align!: any;
  id!: any;
}
