// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatFabAnchor } from "@angular/material/button";

/**
 * Material Design floating action button (FAB) component for anchor elements. Anchor elements
are used to provide links for the user to navigate across different routes or pages.
See https://material.io/components/buttons-floating-action-button/

The `MatFabAnchor` class has two appearances: normal and extended.
 */
@directiveInterface({ selector: "a[mat-fab]" })
export class MatFabAnchorDirectiveInterface {
  extended!: any;
}
