// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatListItemTitle } from "@angular/material/list";

/**
 * Directive capturing the title of a list item. A list item usually consists of a
title and optional secondary or tertiary lines.

Text content for the title never wraps. There can only be a single title per list item.
 */
@directiveInterface({ selector: "[matListItemTitle]" })
export class MatListItemTitleDirectiveInterface {
}
