// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatNestedTreeNode } from "@angular/material/tree";

/**
 * Wrapper for the CdkTree nested node with Material design styles.
 */
@componentInterface({ selector: "mat-nested-tree-node" })
export class MatNestedTreeNodeComponentInterface {
  matNestedTreeNode!: any;
  disabled!: any;
  tabIndex!: any;
  @output() activation!: any;
  @output() expandedChange!: any;
}
