// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatSortHeader } from "@angular/material/sort";

/**
 * Applies sorting behavior (click to change sort) and styles to an element, including an
arrow to display the current sort direction.

Must be provided with an id and contained within a parent MatSort directive.

If used on header cells in a CdkTable, it will automatically default its id from its containing
column definition.
 */
@directiveInterface({ selector: "[mat-sort-header]" })
export class MatSortHeaderDirectiveInterface {
  "mat-sort-header"!: any;
  arrowPosition!: any;
  start!: any;
  disabled!: any;
  sortActionDescription!: any;
  disableClear!: any;
}
