// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatAutocompleteTrigger } from "@angular/material/autocomplete";

/**
 * Base class with all of the `MatAutocompleteTrigger` functionality.
 */
@directiveInterface({ selector: "input[matAutocomplete],textarea[matAutocomplete]" })
export class MatAutocompleteTriggerDirectiveInterface {
  matAutocomplete!: any;
  matAutocompletePosition!: any;
  matAutocompleteConnectedTo!: any;
  autocomplete!: any;
  matAutocompleteDisabled!: any;
}
