// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatChipAvatar } from "@angular/material/chips";

/**
 * Avatar image within a chip.
 */
@componentInterface({ selector: "[matChipAvatar],mat-chip-avatar" })
export class MatChipAvatarComponentInterface {
}
