// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatSelectionList } from "@angular/material/list";

@componentInterface({ selector: "mat-selection-list", acceptsChildren: true })
export class MatSelectionListComponentInterface {
  color!: any;
  compareWith!: any;
  multiple!: any;
  hideSingleSelectionIndicator!: any;
  disabled!: any;
  @output() selectionChange!: any;
}
