// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatCellDef } from "@angular/material/table";

/**
 * Cell definition for the mat-table.
Captures the template of a column's data row cell as well as cell-specific properties.
 */
@directiveInterface({ selector: "[matCellDef]" })
export class MatCellDefDirectiveInterface {
}
