// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatListItem } from "@angular/material/list";

@componentInterface({ selector: "a[mat-list-item],button[mat-list-item],mat-list-item", acceptsChildren: true })
export class MatListItemComponentInterface {
  activated!: any;
}
