// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatDialogActions } from "@angular/material/dialog";

/**
 * Container for the bottom action buttons in a dialog.
Stays fixed to the bottom when scrolling.
 */
@componentInterface({ selector: "[mat-dialog-actions],[matDialogActions],mat-dialog-actions" })
export class MatDialogActionsComponentInterface {
  align!: any;
}
