// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatChipGrid } from "@angular/material/chips";

/**
 * An extension of the MatChipSet component used with MatChipRow chips and
the matChipInputFor directive.
 */
@componentInterface({ selector: "mat-chip-grid", acceptsChildren: true })
export class MatChipGridComponentInterface {
  disabled!: any;
  placeholder!: any;
  required!: any;
  value!: any;
  errorStateMatcher!: any;
  @output() change!: any;
  @output() valueChange!: any;
}
