// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatOption } from "@angular/material/core";

/**
 * Single option inside of a `<mat-select>` element.
 */
@componentInterface({ selector: "mat-option", acceptsChildren: true })
export class MatOptionComponentInterface {
  value!: any;
  id!: any;
  disabled!: any;
  @output() onSelectionChange!: any;
}
