// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatError } from "@angular/material/input";

/**
 * Single error message to be shown underneath the form-field.
 */
@componentInterface({ selector: "[matError],mat-error" })
export class MatErrorComponentInterface {
  id!: any;
}
