// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { MatStepper } from "@angular/material/stepper";

@directiveInterface({ selector: "[matStepper],mat-horizontal-stepper,mat-stepper,mat-vertical-stepper" })
export class MatStepperDirectiveInterface {
  disableRipple!: any;
  color!: any;
  labelPosition!: any;
  headerPosition!: any;
  animationDuration!: any;
  @output() animationDone!: any;
}
