// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";

@componentInterface({ selector: "ng-container", acceptsChildren: true })
export class NgContainerComponentInterface {
}
