// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { NgClass } from "@angular/common";

@directiveInterface({ selector: "[ngClass]" })
export class NgClassDirectiveInterface {
  class!: any;
  ngClass!: any;
}
