// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { FormsModule } from "@angular/forms";

@directiveInterface({ selector: "[ngForm],form:not([ngNoForm]):not([formGroup]),ng-form" })
export class NgFormDirectiveInterface {
  ngFormOptions!: any;
  @output() ngSubmit!: any;
}
