// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { NgForm } from "@angular/forms";

@componentInterface({ selector: "[ngForm],form:not([ngNoForm]):not([formGroup]),ng-form" })
export class NgFormComponentInterface {
  ngFormOptions!: any;
  @output() ngSubmit!: any;
}
