// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { NgSwitchDefault } from "@angular/common";

@directiveInterface({ selector: "[ngSwitchDefault]" })
export class NgSwitchDefaultDirectiveInterface {
}
