// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { PortalHostDirective } from "@angular/cdk/portal";

@directiveInterface({ selector: "[cdkPortalHost],[portalHost]" })
export class PortalHostDirectiveDirectiveInterface {
  cdkPortalHost!: any;
}
