// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { SchemaFormTypescriptFieldComponent } from "@apexdesigner/schema-forms";

/**
 * A TypeScript/JavaScript code editor field using Monaco editor.
Provides syntax highlighting, autocomplete, and type checking for TypeScript expressions.
Context types, variables, and functions can be provided via SchemaFormsTypescriptService.
 */
@componentInterface({ selector: "sf-typescript-field", acceptsChildren: true })
export class SchemaFormTypescriptFieldComponentComponentInterface {
  control!: any;
  placeholder!: any;
  label!: any;
  hideHelpText!: any;
  @output() enterPressed!: any;
}
