// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { SchemaFormRegexFieldComponent } from "@apexdesigner/schema-forms";

/**
 * A regular expression input field that binds to a SchemaFormControl.
Validates regex syntax and provides a test mode to try patterns against sample text.
 */
@componentInterface({ selector: "sf-regex-field", acceptsChildren: true })
export class SchemaFormRegexFieldComponentComponentInterface {
  control!: any;
  placeholder!: any;
  hideHelpText!: any;
  label!: any;
  @output() enterPressed!: any;
}
