// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { SchemaFormNumberFieldComponent } from "@apexdesigner/schema-forms";

/**
 * A numeric input field that binds to a SchemaFormControl.
Handles number and integer schema types with appropriate input validation.
 */
@componentInterface({ selector: "sf-number-field", acceptsChildren: true })
export class SchemaFormNumberFieldComponentComponentInterface {
  control!: any;
  label!: any;
  placeholder!: any;
  hideHelpText!: any;
  @output() enterPressed!: any;
}
