// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { SchemaFormTypescriptTypeFieldComponent } from "@apexdesigner/schema-forms";

/**
 * A dropdown select field that displays TypeScript types registered in the TypescriptService.
The options are dynamically populated from SchemaFormsTypescriptService.types().

Requires SchemaFormsTypescriptService to be provided in the component tree.
 */
@componentInterface({ selector: "sf-typescript-type-field", acceptsChildren: true })
export class SchemaFormTypescriptTypeFieldComponentComponentInterface {
  control!: any;
  label!: any;
  placeholder!: any;
  hideHelpText!: any;
  @output() enterPressed!: any;
}
