// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { SchemaFormTextareaFieldComponent } from "@apexdesigner/schema-forms";

/**
 * A multi-line text input field that binds to a SchemaFormControl.
Uses cdkTextareaAutosize to automatically resize based on content.
 */
@componentInterface({ selector: "sf-textarea-field", acceptsChildren: true })
export class SchemaFormTextareaFieldComponentComponentInterface {
  control!: any;
  label!: any;
  placeholder!: any;
  hideHelpText!: any;
}
