// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { SchemaFormTextFieldComponent } from "@apexdesigner/schema-forms";

/**
 * A text input field that binds to a SchemaFormControl.
Supports auto-formatting (camelCase, PascalCase, etc.) on blur via the `x-auto-format` schema property.
 */
@componentInterface({ selector: "sf-text-field", acceptsChildren: true })
export class SchemaFormTextFieldComponentComponentInterface {
  control!: any;
  placeholder!: any;
  hideHelpText!: any;
  label!: any;
  @output() enterPressed!: any;
}
