// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { SchemaFormDurationFieldComponent } from "@apexdesigner/schema-forms";

/**
 * A duration input field that binds to a SchemaFormControl.
Stores values as ISO 8601 duration strings (e.g., PT5H, P3D).
Features an autocomplete for common durations (seconds, minutes, hours, days, weeks, months, quarters, years).
 */
@componentInterface({ selector: "sf-duration-field", acceptsChildren: true })
export class SchemaFormDurationFieldComponentComponentInterface {
  control!: any;
  placeholder!: any;
  hideHelpText!: any;
  label!: any;
}
