import type { DesignGenerator, DesignMetadata, GenerationContext } from '@apexdesigner/generator';
import { isLibrary } from '@apexdesigner/generator';
import { getClassByBase, getDescription } from '@apexdesigner/utilities';
import { kebabCase, pascalCase } from 'change-case';
import createDebug from 'debug';

const Debug = createDebug('ad3:generators:dataSourceType');

const dataSourceTypeGenerator: DesignGenerator = {
  name: 'data-source-type',

  triggers: [
    {
      metadataType: 'DataSource',
      condition: (metadata) => !isLibrary(metadata),
    }
  ],

  outputs: (metadata: DesignMetadata) => [
    `design/@types/data-sources/${kebabCase(metadata.name)}.d.ts`
  ],

  async generate(metadata: DesignMetadata, context: GenerationContext) {
    const debug = Debug.extend('generate');
    debug('name %j', metadata.name);

    const className = pascalCase(metadata.name);
    const applyFunctionName = `apply${className}DataSource`;

    const lines: string[] = [];

    // Add header comment
    lines.push(`// Generated type definitions for ${metadata.name} data source`);
    lines.push('');

    // Add description comment if present
    const dsClass = getClassByBase(metadata.sourceFile, 'DataSource');
    const description = dsClass ? getDescription(dsClass) : undefined;
    if (description) {
      lines.push(...description.split('\n').map(line => `// ${line}`));
      lines.push('');
    }

    // Generate class declaration as placeholder
    // Libraries/projects can override with full property definitions
    lines.push(`export declare class ${className} {`);
    lines.push('  // Properties generated by library or project generators');
    lines.push('}');
    lines.push('');

    // Add apply function declaration
    lines.push(`export function ${applyFunctionName}(target: any): void;`);

    const content = lines.join('\n');

    debug('Generated type file for %j', metadata.name);

    return content;
  }
};

export { dataSourceTypeGenerator };
