// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { AnimationBuilder } from "@angular/animations";

/**
 * An injectable service that produces an animation sequence programmatically within an
Angular component or directive.
Provided by the `BrowserAnimationsModule` or `NoopAnimationsModule`.
 */
@externalType({ injectable: true })
export class AnimationBuilderExternalType {}
