// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { BreakpointObserver } from "@angular/cdk/layout";

/**
 * Utility for checking the matching state of `@media` queries.
 */
@externalType({ injectable: true })
export class BreakpointObserverExternalType {}
