// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { ContentObserver } from "@angular/cdk/observers";

/**
 * An injectable service that allows watching elements for changes to their content.
 */
@externalType({ injectable: true })
export class ContentObserverExternalType {}
