// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { ContextMenuTracker } from "@angular/cdk/menu";

/**
 * Tracks the last open context menu trigger across the entire application.
 */
@externalType({ injectable: true })
export class ContextMenuTrackerExternalType {}
