// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { DefaultMatCalendarRangeStrategy } from "@angular/material/datepicker";

/**
 * Provides the default date range selection behavior.
 */
@externalType({ injectable: true })
export class DefaultMatCalendarRangeStrategyExternalType {}
