// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { Dialog } from "@angular/cdk/dialog";

@externalType({ injectable: true })
export class DialogExternalType {}
