// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { FocusMonitor } from "@angular/cdk/a11y";

/**
 * Monitors mouse and keyboard events to determine the cause of focus events.
 */
@externalType({ injectable: true })
export class FocusMonitorExternalType {}
