// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { FormBuilder } from "@angular/forms";

@externalType({ injectable: true })
export class FormBuilderExternalType {}
