// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { HttpXhrBackend } from "@angular/common/http";

/**
 * Uses `XMLHttpRequest` to send requests to a backend server.
 */
@externalType({ injectable: true })
export class HttpXhrBackendExternalType {}
