// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { InputModalityDetector } from "@angular/cdk/a11y";

/**
 * Service that detects the user's input modality.

This service does not update the input modality when a user navigates with a screen reader
(e.g. linear navigation with VoiceOver, object navigation / browse mode with NVDA, virtual PC
cursor mode with JAWS). This is in part due to technical limitations (i.e. keyboard events do not
fire as expected in these modes) but is also arguably the correct behavior. Navigating with a
screen reader is akin to visually scanning a page, and should not be interpreted as actual user
input interaction.

When a user is not navigating but *interacting* with a screen reader, this service attempts to
update the input modality to keyboard, but in general this service's behavior is largely
undefined.
 */
@externalType({ injectable: true })
export class InputModalityDetectorExternalType {}
