// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { JsonpInterceptor } from "@angular/common/http";

/**
 * Identifies requests with the method JSONP and
shifts them to the `JsonpClientBackend`.
 */
@externalType({ injectable: true })
export class JsonpInterceptorExternalType {}
