// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { LayoutConfigService } from "@apexdesigner/flex-layout";

/**
 * A service that provides configuration and utilities for flex layout components.

Handles gap normalization and provides responsive breakpoint support for
the flex-column, flex-row, and related layout components.
 */
@externalType({ injectable: true })
export class LayoutConfigServiceExternalType {}
