// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { LocationStrategy } from "@angular/common";

/**
 * Enables the `Location` service to read route state from the browser's URL.
Angular provides two strategies:
`HashLocationStrategy` and `PathLocationStrategy`.

Applications should use the `Router` or `Location` services to
interact with application route state.

For instance, `HashLocationStrategy` produces URLs like
<code class="no-auto-link">http://example.com/#/foo</code>,
and `PathLocationStrategy` produces
<code class="no-auto-link">http://example.com/foo</code> as an equivalent URL.

See these two classes for more.
 */
@externalType({ injectable: true })
export class LocationStrategyExternalType {}
