// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { MatSnackBar } from "@angular/material/snack-bar";

/**
 * Service to dispatch Material Design snack bar messages.
 */
@externalType({ injectable: true })
export class MatSnackBarExternalType {}
