// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { Meta } from "@angular/platform-browser";

/**
 * A service for managing HTML `<meta>` tags.

Properties of the `MetaDefinition` object match the attributes of the
HTML `<meta>` tag. These tags define document metadata that is important for
things like configuring a Content Security Policy, defining browser compatibility
and security settings, setting HTTP Headers, defining rich content for social sharing,
and Search Engine Optimization (SEO).

To identify specific `<meta>` tags in a document, use an attribute selection
string in the format `"tag_attribute='value string'"`.
For example, an `attrSelector` value of `"name='description'"` matches a tag
whose `name` attribute has the value `"description"`.
Selectors are used with the `querySelector()` Document method,
in the format `meta[{attrSelector}]`.
 */
@externalType({ injectable: true })
export class MetaExternalType {}
