// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { NgLocaleLocalization } from "@angular/common";

/**
 * Returns the plural case based on the locale
 */
@externalType({ injectable: true })
export class NgLocaleLocalizationExternalType {}
