// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { NoPreloading } from "@angular/router";

@externalType({ injectable: true })
export class NoPreloadingExternalType {}
