// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { NonNullableFormBuilder } from "@angular/forms";

@externalType({ injectable: true })
export class NonNullableFormBuilderExternalType {}
