// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { NoopAnimationDriver } from "@angular/animations/browser";

@externalType({ injectable: true })
export class NoopAnimationDriverExternalType {}
