// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { OverlayKeyboardDispatcher } from "@angular/cdk/overlay";

/**
 * Service for dispatching keyboard events that land on the body to appropriate overlay ref,
if any. It maintains a list of attached overlays to determine best suited overlay based
on event target and order of overlay opens.
 */
@externalType({ injectable: true })
export class OverlayKeyboardDispatcherExternalType {}
