// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { PathLocationStrategy } from "@angular/common";

@externalType({ injectable: true })
export class PathLocationStrategyExternalType {}
