// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { SchemaFormsTypescriptService } from "@apexdesigner/schema-forms";

/**
 * Service for managing TypeScript context for Monaco editor intellisense.

This service is NOT provided in root - it should be provided at the appropriate
scope (e.g., component, route, or module level) to allow different contexts
for different parts of the application.

The service uses Angular signals for reactivity. TypeScript field components
can subscribe to changes using effect().
 */
@externalType({ injectable: true })
export class SchemaFormsTypescriptServiceExternalType {}
