// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { SharedResizeObserver } from "@angular/cdk/observers/private";

/**
 * Allows observing resize events on multiple elements using a shared set of ResizeObserver.
Sharing a ResizeObserver instance is recommended for better performance (see
https://github.com/WICG/resize-observer/issues/59).

Rather than share a single `ResizeObserver`, this class creates one `ResizeObserver` per type
of observed box ('content-box', 'border-box', and 'device-pixel-content-box'). This avoids
later calls to `observe` with a different box type from influencing the events dispatched to
earlier calls.
 */
@externalType({ injectable: true })
export class SharedResizeObserverExternalType {}
