// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { TargetMenuAim } from "@angular/cdk/menu";

/**
 * TargetMenuAim predicts if a user is moving into a submenu. It calculates the
trajectory of the user's mouse movement in the current menu to determine if the
mouse is moving towards an open submenu.

The determination is made by calculating the slope of the users last NUM_POINTS moves where each
pair of points determines if the trajectory line points into the submenu. It uses consensus
approach by checking if at least NUM_POINTS / 2 pairs determine that the user is moving towards
to submenu.
 */
@externalType({ injectable: true })
export class TargetMenuAimExternalType {}
