// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { Testability } from "@angular/core";

/**
 * The Testability service provides testing hooks that can be accessed from
the browser.

Angular applications bootstrapped using an NgModule (via `@NgModule.bootstrap` field) will also
instantiate Testability by default (in both development and production modes).

For applications bootstrapped using the `bootstrapApplication` function, Testability is not
included by default. You can include it into your applications by getting the list of necessary
providers using the `provideProtractorTestingSupport()` function and adding them into the
`options.providers` array. Example:

```ts
import {provideProtractorTestingSupport} from '@angular/platform-browser';

await bootstrapApplication(RootComponent, providers: [provideProtractorTestingSupport()]);
```
 */
@externalType({ injectable: true })
export class TestabilityExternalType {}
