// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { UniqueSelectionDispatcher } from "@angular/cdk/collections";

/**
 * Class to coordinate unique selection based on name.
Intended to be consumed as an Angular service.
This service is needed because native radio change events are only fired on the item currently
being selected, and we still need to uncheck the previous selection.

This service does not *store* any IDs and names because they may change at any time, so it is
less error-prone if they are simply passed through when the events occur.
 */
@externalType({ injectable: true })
export class UniqueSelectionDispatcherExternalType {}
