// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { UrlSerializer } from "@angular/router";

@externalType({ injectable: true })
export class UrlSerializerExternalType {}
