name: CI/CD Failure to Slack

# Trigger when ci-cd workflow completes with failure status
on:
  workflow_run:
    workflows: ["CI/CD"]
    types: [completed]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.head_branch == 'main' }}
    
    steps:
      - name: Send CI/CD failure notification to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "❌ CI/CD workflow failed for <${{ github.event.workflow_run.html_url }}|${{ github.event.workflow_run.head_branch }}> - <${{ github.event.workflow_run.html_url }}|View workflow run>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
