name: Discussion Comment to Slack

# Trigger this workflow when a comment is made on a discussion
on:
  discussion_comment:
    types: [created]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send discussion comment notification to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "💬 ${{ github.event.comment.user.login }} commented on <${{ github.event.discussion.html_url }}|${{ github.event.discussion.title }}> - <${{ github.event.comment.html_url }}|View Comment>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
