name: Issue Comment to Slack

# Trigger this workflow when a comment is made on an issue
on:
  issue_comment:
    types: [created]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send issue comment notification to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "💬 ${{ github.event.comment.user.login }} commented on <${{ github.event.issue.html_url }}|#${{ github.event.issue.number }}: ${{ github.event.issue.title }}> - <${{ github.event.comment.html_url }}|View Comment>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
