name: Issue Close to Slack

# Trigger this workflow when an issue is closed
on:
  issues:
    types: [closed]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send issue close notification to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "✅ ${{ github.event.sender.login }} closed issue <${{ github.event.issue.html_url }}|#${{ github.event.issue.number }}: ${{ github.event.issue.title }}>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
