name: New Discussion to Slack

# Trigger this workflow when a new discussion is created
on:
  discussion:
    types: [created]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send new discussion notification to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "🆕 ${{ github.event.discussion.user.login }} created discussion <${{ github.event.discussion.html_url }}|${{ github.event.discussion.title }}> in ${{ github.event.discussion.category.name }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
