// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { AbstractSecurityStorage } from "angular-auth-oidc-client";

/**
 * Implement this class-interface to create a custom storage.
 */
@externalType({ injectable: true })
export class AbstractSecurityStorageExternalType {}
