// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { ApplicationRef } from "@angular/core";

/**
 * A reference to an Angular application running on a page.
 */
@externalType({ injectable: true })
export class ApplicationRefExternalType {}
