// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { AriaDescriber } from "@angular/cdk/a11y";

/**
 * Utility that creates visually hidden elements with a message content. Useful for elements that
want to use aria-describedby to further describe themselves without adding additional visual
content.
 */
@externalType({ injectable: true })
export class AriaDescriberExternalType {}
