// Generated by @apexdesigner/extract-interfaces
import { pipeInterface } from "@apexdesigner/dsl/pipe-interface";
import { AsyncPipe } from "@angular/common";

@pipeInterface({ selector: "async" })
export class AsyncPipePipeInterface {}
