// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { AuthInterceptor } from "angular-auth-oidc-client";

@externalType({ injectable: true, injectLocally: true })
export class AuthInterceptorExternalType {}
