// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { AutofillMonitor } from "@angular/cdk/text-field";

/**
 * An injectable service that can be used to monitor the autofill state of an input.
Based on the following blog post:
https://medium.com/@brunn/detecting-autofilled-fields-in-javascript-aed598d25da7
 */
@externalType({ injectable: true })
export class AutofillMonitorExternalType {}
