// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { BrowserPlatformLocation } from "@angular/common";

/**
 * `PlatformLocation` encapsulates all of the direct calls to platform APIs.
This class should not be used directly by an application developer. Instead, use
{@link Location}.
 */
@externalType({ injectable: true })
export class BrowserPlatformLocationExternalType {}
