// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkOption } from "@angular/cdk/listbox";

/**
 * A selectable option in a listbox.
 */
@directiveInterface({ selector: "[cdkOption]" })
export class CdkOptionDirectiveInterface {
  id!: any;
  cdkOption!: any;
  cdkOptionTypeaheadLabel!: any;
  cdkOptionDisabled!: any;
  tabindex!: any;
}
