// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkStepHeader } from "@angular/cdk/stepper";

@directiveInterface({ selector: "[cdkStepHeader]" })
export class CdkStepHeaderDirectiveInterface {
}
