// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { CdkFooterCell } from "@angular/cdk/table";

/**
 * Footer cell template container that adds the right classes and role.
 */
@componentInterface({ selector: "cdk-footer-cell,td[cdk-footer-cell]" })
export class CdkFooterCellComponentInterface {
}
