// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { CdkAccordion } from "@angular/cdk/accordion";

/**
 * Directive whose purpose is to manage the expanded state of CdkAccordionItem children.
 */
@componentInterface({ selector: "[cdkAccordion],cdk-accordion" })
export class CdkAccordionComponentInterface {
  multi!: any;
}
