// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkNoDataRow } from "@angular/cdk/table";

/**
 * Row that can be used to display a message when no data is shown in the table.
 */
@directiveInterface({ selector: "ng-template[cdkNoDataRow]" })
export class CdkNoDataRowDirectiveInterface {
}
