// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkTreeNodeDef } from "@angular/cdk/tree";

/**
 * Data node definition for the CdkTree.
Captures the node's template and a when predicate that describes when this node should be used.
 */
@directiveInterface({ selector: "[cdkTreeNodeDef]" })
export class CdkTreeNodeDefDirectiveInterface {
  cdkTreeNodeDefWhen!: any;
}
