// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkAriaLive } from "@angular/cdk/a11y";

/**
 * A directive that works similarly to aria-live, but uses the LiveAnnouncer to ensure compatibility
with a wider range of browsers and screen readers.
 */
@directiveInterface({ selector: "[cdkAriaLive]" })
export class CdkAriaLiveDirectiveInterface {
  cdkAriaLive!: any;
  cdkAriaLiveDuration!: any;
}
