// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkFooterRowDef } from "@angular/cdk/table";

/**
 * Footer row definition for the CDK table.
Captures the footer row's template and other footer properties such as the columns to display.
 */
@directiveInterface({ selector: "[cdkFooterRowDef]" })
export class CdkFooterRowDefDirectiveInterface {
  cdkFooterRowDef!: any;
  cdkFooterRowDefSticky!: any;
}
