// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { CdkTextColumn } from "@angular/cdk/table";

/**
 * Column that simply shows text content for the header and row cells. Assumes that the table
is using the native table implementation (`<table>`).

By default, the name of this column will be the header text and data property accessor.
The header text can be overridden with the `headerText` input. Cell values can be overridden with
the `dataAccessor` input. Change the text justification to the start or end using the `justify`
input.
 */
@componentInterface({ selector: "cdk-text-column", acceptsChildren: true })
export class CdkTextColumnComponentInterface {
  name!: any;
  headerText!: any;
  dataAccessor!: any;
  justify!: any;
}
