// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { CdkCell } from "@angular/cdk/table";

/**
 * Cell template container that adds the right classes and role.
 */
@componentInterface({ selector: "cdk-cell,td[cdk-cell]" })
export class CdkCellComponentInterface {
}
