// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkStepLabel } from "@angular/cdk/stepper";

@directiveInterface({ selector: "[cdkStepLabel]" })
export class CdkStepLabelDirectiveInterface {
}
