// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { CdkAutofill } from "@angular/cdk/text-field";

/**
 * A directive that can be used to monitor the autofill state of an input.
 */
@directiveInterface({ selector: "[cdkAutofill]" })
export class CdkAutofillDirectiveInterface {
  @output() cdkAutofill!: any;
}
