// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { CdkDrag } from "@angular/cdk/drag-drop";

/**
 * Element that can be moved inside a CdkDropList container.
 */
@directiveInterface({ selector: "[cdkDrag]" })
export class CdkDragDirectiveInterface {
  cdkDragData!: any;
  cdkDragLockAxis!: any;
  cdkDragRootElement!: any;
  cdkDragBoundary!: any;
  cdkDragStartDelay!: any;
  cdkDragFreeDragPosition!: any;
  cdkDragDisabled!: any;
  cdkDragConstrainPosition!: any;
  cdkDragPreviewClass!: any;
  cdkDragPreviewContainer!: any;
  cdkDragScale!: any;
  @output() cdkDragStarted!: any;
  @output() cdkDragReleased!: any;
  @output() cdkDragEnded!: any;
  @output() cdkDragEntered!: any;
  @output() cdkDragExited!: any;
  @output() cdkDragDropped!: any;
  @output() cdkDragMoved!: any;
}
