// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { CdkContextMenuTrigger } from "@angular/cdk/menu";

/**
 * A directive that opens a menu when a user right-clicks within its host element.
It is aware of nested context menus and will trigger only the lowest level non-disabled context menu.
 */
@directiveInterface({ selector: "[cdkContextMenuTriggerFor]" })
export class CdkContextMenuTriggerDirectiveInterface {
  cdkContextMenuTriggerFor!: any;
  cdkContextMenuPosition!: any;
  cdkContextMenuTriggerData!: any;
  cdkContextMenuDisabled!: any;
  @output() cdkContextMenuOpened!: any;
  @output() cdkContextMenuClosed!: any;
}
