// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkDropListGroup } from "@angular/cdk/drag-drop";

/**
 * Declaratively connects sibling `cdkDropList` instances together. All of the `cdkDropList`
elements that are placed inside a `cdkDropListGroup` will be connected to each other
automatically. Can be used as an alternative to the `cdkDropListConnectedTo` input
from `cdkDropList`.
 */
@directiveInterface({ selector: "[cdkDropListGroup]" })
export class CdkDropListGroupDirectiveInterface {
  cdkDropListGroupDisabled!: any;
}
