// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkVirtualForOf } from "@angular/cdk/scrolling";

/**
 * A directive similar to `ngForOf` to be used for rendering data inside a virtual scrolling
container.
 */
@directiveInterface({ selector: "[cdkVirtualFor][cdkVirtualForOf]" })
export class CdkVirtualForOfDirectiveInterface {
  cdkVirtualForOf!: any;
  cdkVirtualForTrackBy!: any;
  cdkVirtualForTemplate!: any;
  cdkVirtualForTemplateCacheSize!: any;
}
