// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkDragHandle } from "@angular/cdk/drag-drop";

/**
 * Handle that can be used to drag a CdkDrag instance.
 */
@directiveInterface({ selector: "[cdkDragHandle]" })
export class CdkDragHandleDirectiveInterface {
  cdkDragHandleDisabled!: any;
}
