// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class CdkTextColumnJustifyType extends BaseType<string> {}

applyValidValues(CdkTextColumnJustifyType, [
  "start",
  "end",
  "center",
]);
