// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkFixedSizeVirtualScroll } from "@angular/cdk/scrolling";

/**
 * A virtual scroll strategy that supports fixed-size items.
 */
@directiveInterface({ selector: "cdk-virtual-scroll-viewport[itemSize]" })
export class CdkFixedSizeVirtualScrollDirectiveInterface {
  itemSize!: any;
  minBufferPx!: any;
  maxBufferPx!: any;
}
