// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { CdkHeaderCell } from "@angular/cdk/table";

/**
 * Header cell template container that adds the right classes and role.
 */
@componentInterface({ selector: "cdk-header-cell,th[cdk-header-cell]" })
export class CdkHeaderCellComponentInterface {
}
