// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkHeaderCellDef } from "@angular/cdk/table";

/**
 * Header cell definition for a CDK table.
Captures the template of a column's header cell and as well as cell-specific properties.
 */
@directiveInterface({ selector: "[cdkHeaderCellDef]" })
export class CdkHeaderCellDefDirectiveInterface {
}
