// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { CdkObserveContent } from "@angular/cdk/observers";

/**
 * Directive that triggers a callback whenever the content of
its associated element has changed.
 */
@directiveInterface({ selector: "[cdkObserveContent]" })
export class CdkObserveContentDirectiveInterface {
  cdkObserveContentDisabled!: any;
  debounce!: any;
  @output() cdkObserveContent!: any;
}
