// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { CdkFooterRow } from "@angular/cdk/table";

/**
 * Footer template container that contains the cell outlet. Adds the right class and role.
 */
@componentInterface({ selector: "cdk-footer-row,tr[cdk-footer-row]", acceptsChildren: true })
export class CdkFooterRowComponentInterface {
}
