// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkTreeNodePadding } from "@angular/cdk/tree";

/**
 * Indent for the children tree dataNodes.
This directive will add left-padding to the node to show hierarchy.
 */
@directiveInterface({ selector: "[cdkTreeNodePadding]" })
export class CdkTreeNodePaddingDirectiveInterface {
  cdkTreeNodePadding!: any;
  cdkTreeNodePaddingIndent!: any;
}
