// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkHeaderCell } from "@angular/cdk/table";

/**
 * Header cell template container that adds the right classes and role.
 */
@directiveInterface({ selector: "cdk-header-cell,th[cdk-header-cell]" })
export class CdkHeaderCellDirectiveInterface {
}
