// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class CdkDragLockAxisType extends BaseType<string> {}

applyValidValues(CdkDragLockAxisType, [
  "x",
  "y",
]);
