// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkStepperNext } from "@angular/cdk/stepper";

/**
 * Button that moves to the next step in a stepper workflow.
 */
@directiveInterface({ selector: "button[cdkStepperNext]" })
export class CdkStepperNextDirectiveInterface {
  type!: any;
}
