// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class CdkDropListOrientationType extends BaseType<string> {}

applyValidValues(CdkDropListOrientationType, [
  "horizontal",
  "vertical",
  "mixed",
]);
