// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { CdkCopyToClipboard } from "@angular/cdk/clipboard";

/**
 * Cdk Copy To Clipboard
 *
 * Provides behavior for a button that when clicked copies content into user's
 * clipboard.
 */
@directiveInterface({ selector: "[cdkCopyToClipboard]" })
export class CdkCopyToClipboardDirectiveInterface {
  cdkCopyToClipboard!: any;
  cdkCopyToClipboardAttempts!: any;
  @output() cdkCopyToClipboardCopied!: any;
}
