// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { CdkVirtualScrollViewport } from "@angular/cdk/scrolling";

/**
 * A viewport that virtualizes its scrolling with the help of `CdkVirtualForOf`.
 */
@componentInterface({ selector: "cdk-virtual-scroll-viewport", acceptsChildren: true })
export class CdkVirtualScrollViewportComponentInterface {
  orientation!: any;
  appendOnly!: any;
  @output() scrolledIndexChange!: any;
}
