// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { CdkListbox } from "@angular/cdk/listbox";

@directiveInterface({ selector: "[cdkListbox]" })
export class CdkListboxDirectiveInterface {
  id!: any;
  tabindex!: any;
  cdkListboxValue!: any;
  cdkListboxMultiple!: any;
  cdkListboxDisabled!: any;
  cdkListboxUseActiveDescendant!: any;
  cdkListboxOrientation!: any;
  cdkListboxCompareWith!: any;
  cdkListboxNavigationWrapDisabled!: any;
  cdkListboxNavigatesDisabledOptions!: any;
  @output() cdkListboxValueChange!: any;
}
