// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkTreeNodeToggle } from "@angular/cdk/tree";

/**
 * Node toggle to expand and collapse the node.
 */
@directiveInterface({ selector: "[cdkTreeNodeToggle]" })
export class CdkTreeNodeToggleDirectiveInterface {
  cdkTreeNodeToggleRecursive!: any;
}
