// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkCell } from "@angular/cdk/table";

/**
 * Cell template container that adds the right classes and role.
 */
@directiveInterface({ selector: "cdk-cell,td[cdk-cell]" })
export class CdkCellDirectiveInterface {
}
