// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkTrapFocus } from "@angular/cdk/a11y";

/**
 * Directive for trapping focus within a region.
 */
@directiveInterface({ selector: "[cdkTrapFocus]" })
export class CdkTrapFocusDirectiveInterface {
  cdkTrapFocus!: any;
  cdkTrapFocusAutoCapture!: any;
}
