// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { CdkConnectedOverlay } from "@angular/cdk/overlay";

/**
 * Directive to facilitate declarative creation of an
Overlay using a FlexibleConnectedPositionStrategy.
 */
@directiveInterface({ selector: "[cdk-connected-overlay],[cdkConnectedOverlay],[connected-overlay]" })
export class CdkConnectedOverlayDirectiveInterface {
  cdkConnectedOverlayOrigin!: any;
  cdkConnectedOverlayPositions!: any;
  cdkConnectedOverlayPositionStrategy!: any;
  cdkConnectedOverlayOffsetX!: any;
  cdkConnectedOverlayOffsetY!: any;
  cdkConnectedOverlayWidth!: any;
  cdkConnectedOverlayHeight!: any;
  cdkConnectedOverlayMinWidth!: any;
  cdkConnectedOverlayMinHeight!: any;
  cdkConnectedOverlayBackdropClass!: any;
  cdkConnectedOverlayPanelClass!: any;
  cdkConnectedOverlayViewportMargin!: any;
  cdkConnectedOverlayScrollStrategy!: any;
  cdkConnectedOverlayOpen!: any;
  cdkConnectedOverlayDisableClose!: any;
  cdkConnectedOverlayTransformOriginOn!: any;
  cdkConnectedOverlayHasBackdrop!: any;
  cdkConnectedOverlayLockPosition!: any;
  cdkConnectedOverlayFlexibleDimensions!: any;
  cdkConnectedOverlayGrowAfterOpen!: any;
  cdkConnectedOverlayPush!: any;
  cdkConnectedOverlayDisposeOnNavigation!: any;
  @output() backdropClick!: any;
  @output() positionChange!: any;
  @output() attach!: any;
  @output() detach!: any;
  @output() overlayKeydown!: any;
  @output() overlayOutsideClick!: any;
}
