// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { CdkMenuItem } from "@angular/cdk/menu";

/**
 * Directive which provides the ability for an element to be focused and navigated to using the
keyboard when residing in a CdkMenu, CdkMenuBar, or CdkMenuGroup. It performs user defined
behavior when clicked.
 */
@directiveInterface({ selector: "[cdkMenuItem]" })
export class CdkMenuItemDirectiveInterface {
  cdkMenuItemDisabled!: any;
  cdkMenuitemTypeaheadLabel!: any;
  @output() cdkMenuItemTriggered!: any;
}
