// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkPortal } from "@angular/cdk/portal";

/**
 * Directive version of a `TemplatePortal`. Because the directive *is* a TemplatePortal,
the directive instance itself can be attached to a host, enabling declarative use of portals.
 */
@directiveInterface({ selector: "[cdkPortal]" })
export class CdkPortalDirectiveInterface {
}
