// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkAccordion } from "@angular/cdk/accordion";

/**
 * Directive whose purpose is to manage the expanded state of CdkAccordionItem children.
 */
@directiveInterface({ selector: "[cdkAccordion],cdk-accordion" })
export class CdkAccordionDirectiveInterface {
  multi!: any;
}
