// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { CdkMenuGroup } from "@angular/cdk/menu";

/**
 * A grouping container for `CdkMenuItemRadio` instances, similar to a `role="radiogroup"` element.
 */
@directiveInterface({ selector: "[cdkMenuGroup]" })
export class CdkMenuGroupDirectiveInterface {
}
