// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from '@apexdesigner/dsl/directive-interface';
import { CdkVirtualScrollableWindow } from '@angular/cdk/scrolling';

/**
 * Cdk Virtual Scrollable Window
 *
 * Provides as virtual scrollable for the global / window scrollbar.
 */
@directiveInterface({ selector: 'cdk-virtual-scroll-viewport[scrollWindow]' })
export class CdkVirtualScrollableWindowDirectiveInterface {}
