// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { ChangeDetectorRef } from "@angular/core";

@externalType({ injectable: true })
export class ChangeDetectorRefExternalType {}
