// Generated by @apexdesigner/extract-interfaces
import { externalType } from '@apexdesigner/dsl';
import { ChangeDetectorRef } from '@angular/core';

/**
 * Change Detector Ref
 */
@externalType({ injectable: true })
export class ChangeDetectorRefExternalType {}
