// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { Clipboard } from "@angular/cdk/clipboard";

/**
 * A service for copying text to the clipboard.
 */
@externalType({ injectable: true })
export class ClipboardExternalType {}
