// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { Compiler } from "@angular/core";

/**
 * Low-level service for running the angular compiler during runtime
to create {@link ComponentFactory}s, which
can later be used to create and render a Component instance.

Each `@NgModule` provides an own `Compiler` to its injector,
that will use the directives/pipes of the ng module for compilation
of components.
 */
@externalType({ injectable: true })
export class CompilerExternalType {}
