// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { ConfigurationService } from "angular-auth-oidc-client";

@externalType({ injectable: true })
export class ConfigurationServiceExternalType {}
