// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { ConfigurableFocusTrapFactory } from "@angular/cdk/a11y";

/**
 * Factory that allows easy instantiation of configurable focus traps.
 */
@externalType({ injectable: true })
export class ConfigurableFocusTrapFactoryExternalType {}
