// Generated by @apexdesigner/extract-interfaces
import { pipeInterface } from "@apexdesigner/dsl/pipe-interface";
import { CurrencyPipe } from "@angular/common";

@pipeInterface({ selector: "currency" })
export class CurrencyPipePipeInterface {}
