// Generated by @apexdesigner/extract-interfaces
import { pipeInterface } from "@apexdesigner/dsl/pipe-interface";
import { DecimalPipe } from "@angular/common";

@pipeInterface({ selector: "number" })
export class DecimalPipePipeInterface {}
