// Generated by @apexdesigner/extract-interfaces
import { externalType } from '@apexdesigner/dsl';
import { DefaultMatCalendarRangeStrategy } from '@angular/material/datepicker';

/**
 * Default Mat Calendar Range Strategy
 *
 * Provides the default date range selection behavior.
 */
@externalType({ injectable: true, injectLocally: true })
export class DefaultMatCalendarRangeStrategyExternalType {}
