// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { Directionality } from "@angular/cdk/bidi";

/**
 * The directionality (LTR / RTL) context for the application (or a subtree of it).
Exposes the current direction and a stream of direction changes.
 */
@externalType({ injectable: true })
export class DirectionalityExternalType {}
