// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { DragDrop } from "@angular/cdk/drag-drop";

/**
 * Service that allows for drag-and-drop functionality to be attached to DOM elements.
 */
@externalType({ injectable: true })
export class DragDropExternalType {}
