// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { DtColumnComponent } from "@apexdesigner/declarative-tables";

/**
 * Defines a column configuration for the dt-table component.

Each column can display a property from the data source, apply transformations,
or render custom content using a template.
 */
@componentInterface({ selector: "dt-column", acceptsChildren: true })
export class DtColumnComponentComponentInterface {
  property!: any;
  header!: any;
  default!: any;
  prefix!: any;
  pipe!: any;
  align!: any;
}
