// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { DtEmptyStateComponent } from "@apexdesigner/declarative-tables";

/**
 * Dt Empty State Component
 *
 * Container for custom empty state content displayed when the table has no data.
 *
 * This component is shown when the parent dt-table's dataSource is an empty array.
 * Content projected into this component will be displayed in place of the empty table.
 *
 * @example
 * ```html
 * <dt-table [dataSource]="items">
 * <dt-column property="name"></dt-column>
 * <dt-empty-state>
 * <p>No items found. Try adjusting your search criteria.</p>
 * </dt-empty-state>
 * </dt-table>
 * ```
 *
 * @see DtTableComponent
 */
@componentInterface({ selector: "dt-empty-state", acceptsChildren: true })
export class DtEmptyStateComponentComponentInterface {
}
