// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { DtTableComponent } from "@apexdesigner/declarative-tables";

/**
 * A declarative data table component built on Angular Material.

Displays tabular data with automatic column configuration, built-in loading and empty states,
and support for various data transformations through Angular pipes.
 */
@componentInterface({ selector: "dt-table", acceptsChildren: true })
export class DtTableComponentComponentInterface {
  dataSource!: any;
  routerLinkTemplate!: any;
  routeFunction!: any;
}
