// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { ElementRef } from "@angular/core";

@externalType({ injectable: true })
export class ElementRefExternalType {}
