// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { ErrorStateMatcher } from "@angular/material/core";

/**
 * Provider that defines how form controls behave with regards to displaying error messages.
 */
@externalType({ injectable: true })
export class ErrorStateMatcherExternalType {}
