// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { EventManager } from "@angular/platform-browser";

/**
 * An injectable service that provides event management for Angular
through a browser plug-in.
 */
@externalType({ injectable: true })
export class EventManagerExternalType {}
