// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { FetchBackend } from "@angular/common/http";

/**
 * Uses `fetch` to send requests to a backend server.

This `FetchBackend` requires the support of the
[Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) which is available on all
supported browsers and on Node.js v18 or later.
 */
@externalType({ injectable: true })
export class FetchBackendExternalType {}
