// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { FlexColumnComponent } from "@apexdesigner/flex-layout";

/**
 * A flex container component that arranges its children in a vertical column.
 */
@componentInterface({ selector: "flex-column", acceptsChildren: true })
export class FlexColumnComponentComponentInterface {
  gap!: any;
  fitContent!: any;
}
