// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { ReactiveFormsModule } from "@angular/forms";

@directiveInterface({ selector: "[formGroup]" })
export class FormGroupDirectiveDirectiveInterface {
  formGroup!: any;
  @output() ngSubmit!: any;
}
