// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { ReactiveFormsModule } from "@angular/forms";

@directiveInterface({ selector: "[formControl]" })
export class FormControlDirectiveDirectiveInterface {
  formControl!: any;
  disabled!: any;
  ngModel!: any;
  @output() ngModelChange!: any;
}
