// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from '@apexdesigner/dsl/directive-interface';
import { ReactiveFormsModule } from '@angular/forms';

/**
 * Form Control Directive
 *
 * @description
 * Synchronizes a standalone `FormControl` instance to a form control element.
 *
 * Note that support for using the `ngModel` input property and `ngModelChange` event with reactive
 * form directives was deprecated in Angular v6 and is scheduled for removal in
 * a future version of Angular.
 *
 * @see [Reactive Forms Guide](guide/forms/reactive-forms)
 * @see {@link FormControl}
 * @see {@link AbstractControl}
 *
 * @usageNotes
 *
 * The following example shows how to register a standalone control and set its value.
 *
 * {@example forms/ts/simpleFormControl/simple_form_control_example.ts region='Component'}
 *
 * @ngModule ReactiveFormsModule
 * @publicApi
 */
@directiveInterface({ selector: '[formControl]' })
export class FormControlDirectiveDirectiveInterface {
  formControl!: any;
  disabled!: any;
  ngModel!: any;
  @output() ngModelChange!: any;
}
