// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { FullscreenOverlayContainer } from "@angular/cdk/overlay";

/**
 * Alternative to OverlayContainer that supports correct displaying of overlay elements in
Fullscreen mode
https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen

Should be provided in the root component.
 */
@externalType({ injectable: true })
export class FullscreenOverlayContainerExternalType {}
