// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { HammerGestureConfig } from "@angular/platform-browser";

/**
 * An injectable [HammerJS Manager](https://hammerjs.github.io/api/#hammermanager)
for gesture recognition. Configures specific event recognition.
 */
@externalType({ injectable: true })
export class HammerGestureConfigExternalType {}
