// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { HashLocationStrategy } from "@angular/common";

@externalType({ injectable: true })
export class HashLocationStrategyExternalType {}
