// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { HttpClient } from "@angular/common/http";

/**
 * Performs HTTP requests.
This service is available as an injectable class, with methods to perform HTTP requests.
Each request method has multiple signatures, and the return type varies based on
the signature that is called (mainly the values of `observe` and `responseType`).

Note that the `responseType` *options* value is a String that identifies the
single data type of the response.
A single overload version of the method handles each response type.
The value of `responseType` cannot be a union, as the combined signature could imply.
 */
@externalType({ injectable: true })
export class HttpClientExternalType {}
