// Generated by @apexdesigner/extract-interfaces
import { pipeInterface } from "@apexdesigner/dsl/pipe-interface";
import { I18nPluralPipe } from "@angular/common";

@pipeInterface({ selector: "i18nPlural" })
export class I18nPluralPipePipeInterface {}
