// Generated by @apexdesigner/extract-interfaces
import { pipeInterface } from "@apexdesigner/dsl/pipe-interface";
import { I18nSelectPipe } from "@angular/common";

@pipeInterface({ selector: "i18nSelect" })
export class I18nSelectPipePipeInterface {}
