// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { Injector } from "@angular/core";

@externalType({ injectable: true })
export class InjectorExternalType {}
