// Generated by @apexdesigner/extract-interfaces
import { externalType } from '@apexdesigner/dsl';
import { Injector } from '@angular/core';

/**
 * Injector
 */
@externalType({ injectable: true })
export class InjectorExternalType {}
