// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { InteractivityChecker } from "@angular/cdk/a11y";

/**
 * Utility for checking the interactivity of an element, such as whether it is focusable or
tabbable.
 */
@externalType({ injectable: true })
export class InteractivityCheckerExternalType {}
