// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { IterableDiffers } from "@angular/core";

/**
 * A repository of different iterable diffing strategies used by NgFor, NgClass, and others.
 */
@externalType({ injectable: true })
export class IterableDiffersExternalType {}
