// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { JsonpInterceptor } from "@angular/common/http";

/**
 * Jsonp Interceptor
 *
 * Identifies requests with the method JSONP and
 * shifts them to the `JsonpClientBackend`.
 *
 * @see {@link HttpInterceptor}
 *
 * @publicApi
 */
@externalType({ injectable: true })
export class JsonpInterceptorExternalType {}
