// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { JsonpClientBackend } from "@angular/common/http";

/**
 * Processes an `HttpRequest` with the JSONP method,
by performing JSONP style requests.
 */
@externalType({ injectable: true })
export class JsonpClientBackendExternalType {}
