// Generated by @apexdesigner/extract-interfaces
import { pipeInterface } from "@apexdesigner/dsl/pipe-interface";
import { JsonPipe } from "@angular/common";

@pipeInterface({ selector: "json" })
export class JsonPipePipeInterface {}
