// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { KeyValueDiffers } from "@angular/core";

/**
 * A repository of different Map diffing strategies used by NgClass, NgStyle, and others.
 */
@externalType({ injectable: true })
export class KeyValueDiffersExternalType {}
