// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { LiveAnnouncer } from "@angular/cdk/a11y";

@externalType({ injectable: true })
export class LiveAnnouncerExternalType {}
