// Generated by @apexdesigner/extract-interfaces
import { externalType } from '@apexdesigner/dsl';
import { Location } from '@angular/common';

@externalType({ injectable: true, injectLocally: true })
export class LocationExternalType {}
