// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { Location } from "@angular/common";

@externalType({ injectable: true })
export class LocationExternalType {}
