// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatBadge } from "@angular/material/badge";

/**
 * Directive to display a text badge.
 */
@directiveInterface({ selector: "[matBadge]" })
export class MatBadgeDirectiveInterface {
  matBadgeColor!: any;
  matBadgeOverlap!: any;
  matBadgeDisabled!: any;
  matBadgePosition!: any;
  matBadge!: any;
  matBadgeDescription!: any;
  matBadgeSize!: any;
  matBadgeHidden!: any;
}
