// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { MatChipRow } from "@angular/material/chips";

/**
 * An extension of the MatChip component used with MatChipGrid and
the matChipInputFor directive.
 */
@directiveInterface({ selector: "[mat-basic-chip-row],[mat-chip-row],mat-basic-chip-row,mat-chip-row" })
export class MatChipRowDirectiveInterface {
  editable!: any;
  @output() edited!: any;
}
