// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatSliderRangeThumb } from "@angular/material/slider";

/**
 * Mat Slider Range Thumb
 */
@directiveInterface({ selector: "input[matSliderEndThumb],input[matSliderStartThumb]" })
export class MatSliderRangeThumbDirectiveInterface {
}
