// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { MatBottomSheet } from "@angular/material/bottom-sheet";

/**
 * Service to trigger Material Design bottom sheets.
 */
@externalType({ injectable: true })
export class MatBottomSheetExternalType {}
