// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatChipListbox } from "@angular/material/chips";

/**
 * An extension of the MatChipSet component that supports chip selection.
Used with MatChipOption chips.
 */
@componentInterface({ selector: "mat-chip-listbox", acceptsChildren: true })
export class MatChipListboxComponentInterface {
  multiple!: any;
  "aria-orientation"!: any;
  selectable!: any;
  compareWith!: any;
  required!: any;
  hideSingleSelectionIndicator!: any;
  value!: any;
  @output() change!: any;
}
