// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatCardSmImage } from "@angular/material/card";

/**
 * Same as `MatCardImage`, but small.
 */
@directiveInterface({ selector: "[mat-card-sm-image],[matCardImageSmall]" })
export class MatCardSmImageDirectiveInterface {
}
