// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatDialogContainer } from "@angular/material/dialog";

@componentInterface({ selector: "mat-dialog-container", acceptsChildren: true })
export class MatDialogContainerComponentInterface {
}
