// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from '@apexdesigner/dsl/directive-interface';
import { MatLine } from '@angular/material/core';

/**
 * Mat Line
 *
 * Shared directive to count lines inside a text area, such as a list item.
 * Line elements can be extracted with a @ContentChildren(MatLine) query, then
 * counted by checking the query list's length.
 */
@directiveInterface({ selector: '[mat-line],[matLine]' })
export class MatLineDirectiveInterface {}
