// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class MatAutocompleteTriggerPositionType extends BaseType<string> {}

applyValidValues(MatAutocompleteTriggerPositionType, [
  "auto",
  "above",
  "below",
]);
