// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatDatepickerApply } from "@angular/material/datepicker";

/**
 * Button that will close the datepicker and assign the current selection to the data model.
 */
@directiveInterface({ selector: "[matDateRangePickerApply],[matDatepickerApply]" })
export class MatDatepickerApplyDirectiveInterface {
}
