// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatAccordion } from "@angular/material/expansion";

/**
 * Directive for a Material Design Accordion.
 */
@componentInterface({ selector: "mat-accordion" })
export class MatAccordionComponentInterface {
  hideToggle!: any;
  displayMode!: any;
  togglePosition!: any;
}
