// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatHeaderCellDef } from "@angular/material/table";

/**
 * Header cell definition for the mat-table.
Captures the template of a column's header cell and as well as cell-specific properties.
 */
@directiveInterface({ selector: "[matHeaderCellDef]" })
export class MatHeaderCellDefDirectiveInterface {
}
