// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatSnackBarActions } from "@angular/material/snack-bar";

/**
 * Mat Snack Bar Actions
 *
 * Directive that should be applied to the element containing the snack bar's action buttons.
 */
@directiveInterface({ selector: "[matSnackBarActions]" })
export class MatSnackBarActionsDirectiveInterface {
}
