// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatCell } from "@angular/material/table";

/**
 * Cell template container that adds the right classes and role.
 */
@directiveInterface({ selector: "mat-cell,td[mat-cell]" })
export class MatCellDirectiveInterface {
}
