// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatIconAnchor } from "@angular/material/button";

/**
 * Material Design icon button component for anchor elements. This button displays a single
interaction icon that allows users to navigate across different routes or pages.
See https://material.io/develop/web/components/buttons/icon-buttons/
 */
@directiveInterface({ selector: "a[mat-icon-button]" })
export class MatIconAnchorDirectiveInterface {
}
