// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatFooterRowDef } from "@angular/material/table";

/**
 * Footer row definition for the mat-table.
Captures the footer row's template and other footer properties such as the columns to display.
 */
@directiveInterface({ selector: "[matFooterRowDef]" })
export class MatFooterRowDefDirectiveInterface {
  matFooterRowDef!: any;
  matFooterRowDefSticky!: any;
}
