// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatTable } from "@angular/material/table";

@componentInterface({ selector: "mat-table,table[mat-table]", acceptsChildren: true })
export class MatTableComponentInterface {
}
