// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatFooterCell } from "@angular/material/table";

/**
 * Footer cell template container that adds the right classes and role.
 */
@componentInterface({ selector: "mat-footer-cell,td[mat-footer-cell]" })
export class MatFooterCellComponentInterface {
}
