// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class MatChipListboxAriaOrientationType extends BaseType<string> {}

applyValidValues(MatChipListboxAriaOrientationType, [
  "horizontal",
  "vertical",
]);
