// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatFooterRow } from "@angular/material/table";

/**
 * Footer template container that contains the cell outlet. Adds the right class and role.
 */
@directiveInterface({ selector: "mat-footer-row,tr[mat-footer-row]" })
export class MatFooterRowDirectiveInterface {
}
