// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatTabContent } from "@angular/material/tabs";

/**
 * Decorates the `ng-template` tags and reads out the template from it.
 */
@directiveInterface({ selector: "[matTabContent]" })
export class MatTabContentDirectiveInterface {
}
