// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class MatBadgeSizeType extends BaseType<string> {}

applyValidValues(MatBadgeSizeType, [
  "small",
  "medium",
  "large",
]);
