// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatListItemLine } from "@angular/material/list";

/**
 * Directive capturing a line in a list item. A list item usually consists of a
title and optional secondary or tertiary lines.

Text content inside a line never wraps. There can be at maximum two lines per list item.
 */
@directiveInterface({ selector: "[matListItemLine]" })
export class MatListItemLineDirectiveInterface {
}
