// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatStep } from "@angular/material/stepper";

@componentInterface({ selector: "mat-step", acceptsChildren: true })
export class MatStepComponentInterface {
  color!: any;
}
