// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { MatChipInput } from "@angular/material/chips";

/**
 * Directive that adds chip-specific behaviors to an input element inside `<mat-form-field>`.
May be placed inside or outside of a `<mat-chip-grid>`.
 */
@directiveInterface({ selector: "input[matChipInputFor]" })
export class MatChipInputDirectiveInterface {
  matChipInputFor!: any;
  matChipInputAddOnBlur!: any;
  matChipInputSeparatorKeyCodes!: any;
  placeholder!: any;
  id!: any;
  disabled!: any;
  @output() matChipInputTokenEnd!: any;
}
