// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatCalendarHeader } from "@angular/material/datepicker";

/**
 * Default header for MatCalendar
 */
@componentInterface({ selector: "mat-calendar-header", acceptsChildren: true })
export class MatCalendarHeaderComponentInterface {
}
