// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatTabNav } from "@angular/material/tabs";

/**
 * Navigation component matching the styles of the tab group header.
Provides anchored navigation with animated ink bar.
 */
@directiveInterface({ selector: "[mat-tab-nav-bar]" })
export class MatTabNavDirectiveInterface {
  fitInkBarToContent!: any;
  "mat-stretch-tabs"!: any;
  animationDuration!: any;
  backgroundColor!: any;
  disableRipple!: any;
  color!: any;
  tabPanel!: any;
}
