// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatToolbarRow } from "@angular/material/toolbar";

@componentInterface({ selector: "mat-toolbar-row" })
export class MatToolbarRowComponentInterface {
}
