// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatListItem } from "@angular/material/list";

@directiveInterface({ selector: "a[mat-list-item],button[mat-list-item],mat-list-item" })
export class MatListItemDirectiveInterface {
  activated!: any;
}
