// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatTreeNode } from "@angular/material/tree";

/**
 * Wrapper for the CdkTree node with Material design styles.
 */
@componentInterface({ selector: "mat-tree-node" })
export class MatTreeNodeComponentInterface {
  tabIndex!: any;
  disabled!: any;
  @output() activation!: any;
  @output() expandedChange!: any;
}
