// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatChipTrailingIcon } from "@angular/material/chips";

/**
 * Non-interactive trailing icon in a chip.
 */
@componentInterface({ selector: "[matChipTrailingIcon],mat-chip-trailing-icon" })
export class MatChipTrailingIconComponentInterface {
}
