// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatCardLgImage } from "@angular/material/card";

/**
 * Mat Card Lg Image
 *
 * Same as `MatCardImage`, but large.
 */
@directiveInterface({ selector: "[mat-card-lg-image],[matCardImageLarge]" })
export class MatCardLgImageDirectiveInterface {
}
