// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatAnchor } from "@angular/material/button";

/**
 * Material Design button component for anchor elements. Anchor elements are used to provide
links for the user to navigate across different routes or pages.
See https://material.io/components/buttons

The `MatAnchor` class applies to native anchor elements and captures the appearances for
"text button", "outlined button", and "contained button" per the Material Design
specification. `MatAnchor` additionally captures an additional "flat" appearance, which matches
"contained" but without elevation.
 */
@directiveInterface({ selector: "a[mat-button],a[mat-flat-button],a[mat-raised-button],a[mat-stroked-button]" })
export class MatAnchorDirectiveInterface {
}
