// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatMenuContent } from "@angular/material/menu";

/**
 * Menu content that will be rendered lazily once the menu is opened.
 */
@directiveInterface({ selector: "ng-template[matMenuContent]" })
export class MatMenuContentDirectiveInterface {
}
