// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class MatCardActionsAlignType extends BaseType<string> {}

applyValidValues(MatCardActionsAlignType, [
  "start",
  "end",
]);
