// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatDivider } from "@angular/material/list";

@componentInterface({ selector: "mat-divider", acceptsChildren: true })
export class MatDividerComponentInterface {
  vertical!: any;
  inset!: any;
}
