// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatStepHeader } from "@angular/material/stepper";

@componentInterface({ selector: "mat-step-header", acceptsChildren: true })
export class MatStepHeaderComponentInterface {
  state!: any;
  label!: any;
  errorMessage!: any;
  iconOverrides!: any;
  index!: any;
  selected!: any;
  active!: any;
  optional!: any;
  disableRipple!: any;
  color!: any;
}
