// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatStepContent } from "@angular/material/stepper";

/**
 * Content for a `mat-step` that will be rendered lazily.
 */
@directiveInterface({ selector: "ng-template[matStepContent]" })
export class MatStepContentDirectiveInterface {
}
