// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatDatepickerActions } from "@angular/material/datepicker";

/**
 * Container that can be used to project a row of action buttons
to the bottom of a datepicker or date range picker.
 */
@componentInterface({ selector: "mat-date-range-picker-actions,mat-datepicker-actions", acceptsChildren: true })
export class MatDatepickerActionsComponentInterface {
}
