// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { MatStepperIntl } from "@angular/material/stepper";

/**
 * Stepper data that is required for internationalization.
 */
@externalType({ injectable: true })
export class MatStepperIntlExternalType {}
