// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { MatSliderThumb } from "@angular/material/slider";

/**
 * Directive that adds slider-specific behaviors to an input element inside `<mat-slider>`.
Up to two may be placed inside of a `<mat-slider>`.

If one is used, the selector `matSliderThumb` must be used, and the outcome will be a normal
slider. If two are used, the selectors `matSliderStartThumb` and `matSliderEndThumb` must be
used, and the outcome will be a range slider with two slider thumbs.
 */
@directiveInterface({ selector: "input[matSliderThumb]" })
export class MatSliderThumbDirectiveInterface {
  value!: any;
  @output() valueChange!: any;
  @output() dragStart!: any;
  @output() dragEnd!: any;
}
