// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from '@apexdesigner/dsl/component-interface';
import { MatNavList } from '@angular/material/list';

/**
 * Mat Nav List
 */
@componentInterface({ selector: 'mat-nav-list', acceptsChildren: true })
export class MatNavListComponentInterface {}
