// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatStepperIcon } from "@angular/material/stepper";

/**
 * Template to be used to override the icons inside the step header.
 */
@directiveInterface({ selector: "ng-template[matStepperIcon]" })
export class MatStepperIconDirectiveInterface {
  matStepperIcon!: any;
}
