// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatDialogClose } from "@angular/material/dialog";

/**
 * Button that will close the current dialog.
 */
@directiveInterface({ selector: "[mat-dialog-close],[matDialogClose]" })
export class MatDialogCloseDirectiveInterface {
  "aria-label"!: any;
  type!: any;
  "mat-dialog-close"!: any;
  matDialogClose!: any;
}
