// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class MatStepperHeaderPositionType extends BaseType<string> {}

applyValidValues(MatStepperHeaderPositionType, [
  "bottom",
  "top",
]);
