// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatTabGroup } from "@angular/material/tabs";

/**
 * Material design tab-group component. Supports basic tab pairs (label + content) and includes
animated ink-bar, keyboard navigation, and screen reader.
See: https://material.io/design/components/tabs.html
 */
@componentInterface({ selector: "mat-tab-group", acceptsChildren: true })
export class MatTabGroupComponentInterface {
  color!: any;
  fitInkBarToContent!: any;
  "mat-stretch-tabs"!: any;
  "mat-align-tabs"!: any;
  dynamicHeight!: any;
  selectedIndex!: any;
  headerPosition!: any;
  animationDuration!: any;
  contentTabIndex!: any;
  disablePagination!: any;
  disableRipple!: any;
  preserveContent!: any;
  backgroundColor!: any;
  "aria-label"!: any;
  "aria-labelledby"!: any;
  @output() selectedIndexChange!: any;
  @output() focusChange!: any;
  @output() animationDone!: any;
  @output() selectedTabChange!: any;
}
