// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatRow } from "@angular/material/table";

/**
 * Data row template container that contains the cell outlet. Adds the right class and role.
 */
@directiveInterface({ selector: "mat-row,tr[mat-row]" })
export class MatRowDirectiveInterface {
}
