// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatPrefix } from "@angular/material/input";

/**
 * Prefix to be placed in front of the form field.
 */
@directiveInterface({ selector: "[matIconPrefix],[matPrefix],[matTextPrefix]" })
export class MatPrefixDirectiveInterface {
  matTextPrefix!: any;
}
