// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatCardMdImage } from "@angular/material/card";

/**
 * Same as `MatCardImage`, but medium.
 */
@directiveInterface({ selector: "[mat-card-md-image],[matCardImageMedium]" })
export class MatCardMdImageDirectiveInterface {
}
