// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatProgressSpinner } from "@angular/material/progress-spinner";

@componentInterface({ selector: "mat-progress-spinner,mat-spinner", acceptsChildren: true })
export class MatProgressSpinnerComponentInterface {
  color!: any;
  mode!: any;
  value!: any;
  diameter!: any;
  strokeWidth!: any;
}
