// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatFabButton } from "@angular/material/button";

/**
 * Material Design floating action button (FAB) component. These buttons represent the primary
or most common action for users to interact with.
See https://material.io/components/buttons-floating-action-button/

The `MatFabButton` class has two appearances: normal and extended.
 */
@directiveInterface({ selector: "button[mat-fab]" })
export class MatFabButtonDirectiveInterface {
  extended!: any;
}
