// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatRipple } from "@angular/material/core";

@directiveInterface({ selector: "[mat-ripple],[matRipple]" })
export class MatRippleDirectiveInterface {
  matRippleColor!: any;
  matRippleUnbounded!: any;
  matRippleCentered!: any;
  matRippleRadius!: any;
  matRippleAnimation!: any;
  matRippleDisabled!: any;
  matRippleTrigger!: any;
}
