// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatNavList } from "@angular/material/list";

@componentInterface({ selector: "mat-nav-list", acceptsChildren: true })
export class MatNavListComponentInterface {
}
