// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatFormField } from "@angular/material/input";

/**
 * Container for form controls that applies Material Design styling and behavior.
 */
@componentInterface({ selector: "mat-form-field", acceptsChildren: true })
export class MatFormFieldComponentInterface {
  hideRequiredMarker!: any;
  color!: any;
  floatLabel!: any;
  appearance!: any;
  subscriptSizing!: any;
  hintLabel!: any;
}
