// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { MatPaginatorIntl } from "@angular/material/paginator";

/**
 * To modify the labels and text displayed, create a new instance of MatPaginatorIntl and
include it in a custom provider
 */
@externalType({ injectable: true })
export class MatPaginatorIntlExternalType {}
