// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatIconButton } from "@angular/material/button";

/**
 * Material Design icon button component. This type of button displays a single interactive icon for
users to perform an action.
See https://material.io/develop/web/components/buttons/icon-buttons/
 */
@directiveInterface({ selector: "button[mat-icon-button]" })
export class MatIconButtonDirectiveInterface {
}
