// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatCardTitle } from "@angular/material/card";

/**
 * Title of a card, intended for use within `<mat-card>`. This component is an optional
convenience for one variety of card title; any custom title element may be used in its place.

MatCardTitle provides no behaviors, instead serving as a purely visual treatment.
 */
@directiveInterface({ selector: "[mat-card-title],[matCardTitle],mat-card-title" })
export class MatCardTitleDirectiveInterface {
}
