// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatMenu } from "@angular/material/menu";

@componentInterface({ selector: "mat-menu", acceptsChildren: true })
export class MatMenuComponentInterface {
  backdropClass!: any;
  "aria-label"!: any;
  "aria-labelledby"!: any;
  "aria-describedby"!: any;
  xPosition!: any;
  yPosition!: any;
  overlapTrigger!: any;
  hasBackdrop!: any;
  class!: any;
  classList!: any;
  @output() closed!: any;
  @output() close!: any;
}
