// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from '@apexdesigner/dsl/component-interface';
import { MatCell } from '@angular/material/table';

/**
 * Mat Cell
 *
 * Cell template container that adds the right classes and role.
 */
@componentInterface({ selector: 'mat-cell,td[mat-cell]' })
export class MatCellComponentInterface {}
