// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatButtonToggle } from "@angular/material/button-toggle";

/**
 * Single button inside of a toggle group.
 */
@componentInterface({ selector: "mat-button-toggle", acceptsChildren: true })
export class MatButtonToggleComponentInterface {
  "aria-label"!: any;
  "aria-labelledby"!: any;
  id!: any;
  name!: any;
  value!: any;
  tabIndex!: any;
  disableRipple!: any;
  appearance!: any;
  checked!: any;
  disabled!: any;
  disabledInteractive!: any;
  @output() change!: any;
}
