// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class MatStepperLabelPositionType extends BaseType<string> {}

applyValidValues(MatStepperLabelPositionType, [
  "bottom",
  "end",
]);
