// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatLine } from "@angular/material/core";

/**
 * Shared directive to count lines inside a text area, such as a list item.
Line elements can be extracted with a
 */
@directiveInterface({ selector: "[mat-line],[matLine]" })
export class MatLineDirectiveInterface {
}
