// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatTreeNodeToggle } from "@angular/material/tree";

/**
 * Wrapper for the CdkTree's toggle with Material design styles.
 */
@directiveInterface({ selector: "[matTreeNodeToggle]" })
export class MatTreeNodeToggleDirectiveInterface {
  matTreeNodeToggleRecursive!: any;
}
