// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatDatepicker } from "@angular/material/datepicker";

/**
 * Component responsible for managing the datepicker popup/dialog.
 */
@componentInterface({ selector: "mat-datepicker", acceptsChildren: true })
export class MatDatepickerComponentInterface {
}
