// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatTabLink } from "@angular/material/tabs";

/**
 * Link inside a `mat-tab-nav-bar`.
 */
@directiveInterface({ selector: "[mat-tab-link],[matTabLink]" })
export class MatTabLinkDirectiveInterface {
  active!: any;
  disabled!: any;
  disableRipple!: any;
  tabIndex!: any;
  id!: any;
}
