// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatChipRow } from "@angular/material/chips";

/**
 * An extension of the MatChip component used with MatChipGrid and
the matChipInputFor directive.
 */
@componentInterface({ selector: "[mat-basic-chip-row],[mat-chip-row],mat-basic-chip-row,mat-chip-row", acceptsChildren: true })
export class MatChipRowComponentInterface {
  editable!: any;
  @output() edited!: any;
}
