// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatGridList } from "@angular/material/grid-list";

@componentInterface({ selector: "mat-grid-list", acceptsChildren: true })
export class MatGridListComponentInterface {
  cols!: any;
  gutterSize!: any;
  rowHeight!: any;
}
