// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatExpansionPanelActionRow } from "@angular/material/expansion";

/**
 * Actions of a `<mat-expansion-panel>`.
 */
@componentInterface({ selector: "mat-action-row" })
export class MatExpansionPanelActionRowComponentInterface {
}
