// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from '@apexdesigner/dsl/directive-interface';
import { MatTreeNodePadding } from '@angular/material/tree';

/**
 * Mat Tree Node Padding
 *
 * Wrapper for the CdkTree padding with Material design styles.
 */
@directiveInterface({ selector: '[matTreeNodePadding]' })
export class MatTreeNodePaddingDirectiveInterface {
  matTreeNodePadding!: any;
  matTreeNodePaddingIndent!: any;
}
