// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class MatCalendarStartViewType extends BaseType<string> {}

applyValidValues(MatCalendarStartViewType, [
  "month",
  "year",
  "multi-year",
]);
