// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatCalendar } from "@angular/material/datepicker";

/**
 * A calendar that is used as part of the datepicker.
 */
@componentInterface({ selector: "mat-calendar", acceptsChildren: true })
export class MatCalendarComponentInterface {
  headerComponent!: any;
  startAt!: any;
  startView!: any;
  selected!: any;
  minDate!: any;
  maxDate!: any;
  dateFilter!: any;
  dateClass!: any;
  comparisonStart!: any;
  comparisonEnd!: any;
  startDateAccessibleName!: any;
  endDateAccessibleName!: any;
  @output() selectedChange!: any;
  @output() yearSelected!: any;
  @output() monthSelected!: any;
  @output() viewChanged!: any;
}
