// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { MatDialog } from "@angular/material/dialog";

/**
 * Service to open Material Design modal dialogs.
 */
@externalType({ injectable: true })
export class MatDialogExternalType {}
