// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatHeaderRow } from "@angular/material/table";

/**
 * Header template container that contains the cell outlet. Adds the right class and role.
 */
@componentInterface({ selector: "mat-header-row,tr[mat-header-row]", acceptsChildren: true })
export class MatHeaderRowComponentInterface {
}
