// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class MatMenuItemRoleType extends BaseType<string> {}

applyValidValues(MatMenuItemRoleType, [
  "menuitem",
  "menuitemradio",
  "menuitemcheckbox",
]);
