// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatCardImage } from "@angular/material/card";

/**
 * Primary image content for a card, intended for use within `<mat-card>`. Can be applied to
any media element, such as `<img>` or `<picture>`.

This component is an optional convenience for use with other convenience elements, such as
`<mat-card-content>`; any custom media element may be used in its place.

MatCardImage provides no behaviors, instead serving as a purely visual treatment.
 */
@directiveInterface({ selector: "[mat-card-image],[matCardImage]" })
export class MatCardImageDirectiveInterface {
}
