// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatTab } from "@angular/material/tabs";

@componentInterface({ selector: "mat-tab", acceptsChildren: true })
export class MatTabComponentInterface {
  disabled!: any;
  label!: any;
  "aria-label"!: any;
  "aria-labelledby"!: any;
  labelClass!: any;
  bodyClass!: any;
  id!: any;
}
