// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatCardSubtitle } from "@angular/material/card";

/**
 * Sub-title of a card, intended for use within `<mat-card>` beneath a `<mat-card-title>`. This
component is an optional convenience for use with other convenience elements, such as
`<mat-card-title>`.

MatCardSubtitle provides no behaviors, instead serving as a purely visual treatment.
 */
@componentInterface({ selector: "[mat-card-subtitle],[matCardSubtitle],mat-card-subtitle" })
export class MatCardSubtitleComponentInterface {
}
