// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatDateRangePicker } from "@angular/material/datepicker";

/**
 * Component responsible for managing the date range picker popup/dialog.
 */
@componentInterface({ selector: "mat-date-range-picker", acceptsChildren: true })
export class MatDateRangePickerComponentInterface {
}
