// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatInput } from "@angular/material/input";

@directiveInterface({ selector: "input[matInput],input[matNativeControl],select[matNativeControl],textarea[matInput],textarea[matNativeControl]" })
export class MatInputDirectiveInterface {
  disabled!: any;
  id!: any;
  placeholder!: any;
  name!: any;
  required!: any;
  type!: any;
  errorStateMatcher!: any;
  "aria-describedby"!: any;
  value!: any;
  readonly!: any;
  disabledInteractive!: any;
}
