// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { MatDatepickerIntl } from "@angular/material/datepicker";

/**
 * Datepicker data that requires internationalization.
 */
@externalType({ injectable: true })
export class MatDatepickerIntlExternalType {}
