// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatDrawerContent } from "@angular/material/sidenav";

@componentInterface({ selector: "mat-drawer-content", acceptsChildren: true })
export class MatDrawerContentComponentInterface {
}
