// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatSnackBarLabel } from "@angular/material/snack-bar";

/**
 * Directive that should be applied to the text element to be rendered in the snack bar.
 */
@directiveInterface({ selector: "[matSnackBarLabel]" })
export class MatSnackBarLabelDirectiveInterface {
}
