// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatChipRemove } from "@angular/material/chips";

/**
 * Directive to remove the parent chip when the trailing icon is clicked or
when the ENTER key is pressed on it.

Recommended for use with the Material Design "cancel" icon
available at https://material.io/icons/#ic_cancel.

Example:

```
<mat-chip>
  <mat-icon matChipRemove>cancel</mat-icon>
</mat-chip>
```
 */
@directiveInterface({ selector: "[matChipRemove]" })
export class MatChipRemoveDirectiveInterface {
}
