// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatCheckbox } from "@angular/material/checkbox";

@componentInterface({ selector: "mat-checkbox", acceptsChildren: true })
export class MatCheckboxComponentInterface {
  "aria-label"!: any;
  "aria-labelledby"!: any;
  "aria-describedby"!: any;
  "aria-expanded"!: any;
  "aria-controls"!: any;
  "aria-owns"!: any;
  id!: any;
  required!: any;
  labelPosition!: any;
  name!: any;
  value!: any;
  disableRipple!: any;
  tabIndex!: any;
  color!: any;
  disabledInteractive!: any;
  checked!: any;
  disabled!: any;
  indeterminate!: any;
  @output() change!: any;
  @output() indeterminateChange!: any;
}
