// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatToolbar } from "@angular/material/toolbar";

@componentInterface({ selector: "mat-toolbar", acceptsChildren: true })
export class MatToolbarComponentInterface {
  color!: any;
}
