// Generated by @apexdesigner/extract-interfaces
import { externalType } from '@apexdesigner/dsl';
import { MatDialog } from '@angular/material/dialog';

/**
 * Mat Dialog
 *
 * Service to open Material Design modal dialogs.
 */
@externalType({ injectable: true })
export class MatDialogExternalType {}
