// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatTabNavPanel } from "@angular/material/tabs";

/**
 * Tab panel component associated with MatTabNav.
 */
@componentInterface({ selector: "mat-tab-nav-panel", acceptsChildren: true })
export class MatTabNavPanelComponentInterface {
  id!: any;
}
