// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatChipSet } from "@angular/material/chips";

/**
 * Basic container component for the MatChip component.

Extended by MatChipListbox and MatChipGrid for different interaction patterns.
 */
@componentInterface({ selector: "mat-chip-set", acceptsChildren: true })
export class MatChipSetComponentInterface {
  disabled!: any;
  role!: any;
  tabIndex!: any;
}
