// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatSnackBarAction } from "@angular/material/snack-bar";

/**
 * Mat Snack Bar Action
 *
 * Directive that should be applied to each of the snack bar's action buttons.
 */
@directiveInterface({ selector: "[matSnackBarAction]" })
export class MatSnackBarActionDirectiveInterface {
}
