// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatTimepickerToggle } from "@angular/material/timepicker";

/**
 * Button that can be used to open a `mat-timepicker`.
 */
@componentInterface({ selector: "mat-timepicker-toggle", acceptsChildren: true })
export class MatTimepickerToggleComponentInterface {
  for!: any;
  "aria-label"!: any;
  "aria-labelledby"!: any;
  disabled!: any;
  tabIndex!: any;
  disableRipple!: any;
}
