// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class MatBadgePositionType extends BaseType<string> {}

applyValidValues(MatBadgePositionType, [
  "above after",
  "above before",
  "below before",
  "below after",
  "before",
  "after",
  "above",
  "below",
]);
