// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatDrawerContainer } from "@angular/material/sidenav";

/**
 * `<mat-drawer-container>` component.

This is the parent component to one or two `<mat-drawer>`s that validates the state internally
and coordinates the backdrop and content styling.
 */
@componentInterface({ selector: "mat-drawer-container", acceptsChildren: true })
export class MatDrawerContainerComponentInterface {
  autosize!: any;
  hasBackdrop!: any;
  @output() backdropClick!: any;
}
