// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class MatTooltipTouchGesturesType extends BaseType<string> {}

applyValidValues(MatTooltipTouchGesturesType, [
  "auto",
  "on",
  "off",
]);
