// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatRecycleRows } from "@angular/material/table";

/**
 * Enables the recycle view repeater strategy, which reduces rendering latency. Not compatible with
tables that animate rows.
 */
@directiveInterface({ selector: "mat-table[recycleRows],table[mat-table][recycleRows]" })
export class MatRecycleRowsDirectiveInterface {
}
