// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatList } from "@angular/material/list";

@componentInterface({ selector: "mat-list", acceptsChildren: true })
export class MatListComponentInterface {
}
