// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatTreeNodeDef } from "@angular/material/tree";

/**
 * Wrapper for the CdkTree node definition with Material design styles.
Captures the node's template and a when predicate that describes when this node should be used.
 */
@directiveInterface({ selector: "[matTreeNodeDef]" })
export class MatTreeNodeDefDirectiveInterface {
  matTreeNodeDefWhen!: any;
  matTreeNode!: any;
}
