// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatExpansionPanelDescription } from "@angular/material/expansion";

/**
 * Description element of a `<mat-expansion-panel-header>`.
 */
@componentInterface({ selector: "mat-panel-description" })
export class MatExpansionPanelDescriptionComponentInterface {
}
