// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatChipOption } from "@angular/material/chips";

/**
 * An extension of the MatChip component that supports chip selection. Used with MatChipListbox.

Unlike other chips, the user can focus on disabled chip options inside a MatChipListbox. The
user cannot click disabled chips.
 */
@componentInterface({ selector: "[mat-basic-chip-option],[mat-chip-option],mat-basic-chip-option,mat-chip-option", acceptsChildren: true })
export class MatChipOptionComponentInterface {
  selectable!: any;
  selected!: any;
  @output() selectionChange!: any;
}
