// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatAutocomplete } from "@angular/material/autocomplete";

/**
 * Autocomplete component.
 */
@componentInterface({ selector: "mat-autocomplete", acceptsChildren: true })
export class MatAutocompleteComponentInterface {
  "aria-label"!: any;
  "aria-labelledby"!: any;
  displayWith!: any;
  autoActiveFirstOption!: any;
  autoSelectActiveOption!: any;
  requireSelection!: any;
  panelWidth!: any;
  disableRipple!: any;
  class!: any;
  hideSingleSelectionIndicator!: any;
  @output() optionSelected!: any;
  @output() opened!: any;
  @output() closed!: any;
  @output() optionActivated!: any;
}
