// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatHeaderRow } from "@angular/material/table";

/**
 * Header template container that contains the cell outlet. Adds the right class and role.
 */
@directiveInterface({ selector: "mat-header-row,tr[mat-header-row]" })
export class MatHeaderRowDirectiveInterface {
}
