// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatTimepicker } from "@angular/material/timepicker";

/**
 * Renders out a listbox that can be used to select a time of day.
Intended to be used together with `MatTimepickerInput`.
 */
@componentInterface({ selector: "mat-timepicker", acceptsChildren: true })
export class MatTimepickerComponentInterface {
  interval!: any;
  options!: any;
  disableRipple!: any;
  "aria-label"!: any;
  "aria-labelledby"!: any;
  @output() selected!: any;
  @output() opened!: any;
  @output() closed!: any;
}
