// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatExpansionPanelHeader } from "@angular/material/expansion";

/**
 * Header element of a `<mat-expansion-panel>`.
 */
@componentInterface({ selector: "mat-expansion-panel-header", acceptsChildren: true })
export class MatExpansionPanelHeaderComponentInterface {
  expandedHeight!: any;
  collapsedHeight!: any;
  tabIndex!: any;
}
