// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatTabLabel } from "@angular/material/tabs";

/**
 * Used to flag tab labels for use with the portal directive
 */
@directiveInterface({ selector: "[mat-tab-label],[matTabLabel]" })
export class MatTabLabelDirectiveInterface {
}
