// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatStepper } from "@angular/material/stepper";

@componentInterface({ selector: "[matStepper],mat-horizontal-stepper,mat-stepper,mat-vertical-stepper", acceptsChildren: true })
export class MatStepperComponentInterface {
  disableRipple!: any;
  color!: any;
  labelPosition!: any;
  headerPosition!: any;
  animationDuration!: any;
  @output() animationDone!: any;
}
