// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatMenuItem } from "@angular/material/menu";

/**
 * Single item inside a `mat-menu`. Provides the menu item styling and accessibility treatment.
 */
@directiveInterface({ selector: "[mat-menu-item]" })
export class MatMenuItemDirectiveInterface {
  role!: any;
  disabled!: any;
  disableRipple!: any;
}
