// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatRadioGroup } from "@angular/material/radio";

/**
 * A group of radio buttons. May contain one or more `<mat-radio-button>` elements.
 */
@componentInterface({ selector: "mat-radio-group" })
export class MatRadioGroupComponentInterface {
  color!: any;
  name!: any;
  labelPosition!: any;
  value!: any;
  selected!: any;
  disabled!: any;
  required!: any;
  disabledInteractive!: any;
  @output() change!: any;
}
