// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatExpansionPanel } from "@angular/material/expansion";

/**
 * This component can be used as a single element to show expandable content, or as one of
multiple children of an element with the MatAccordion directive attached.
 */
@componentInterface({ selector: "mat-expansion-panel", acceptsChildren: true })
export class MatExpansionPanelComponentInterface {
  hideToggle!: any;
  togglePosition!: any;
  @output() afterExpand!: any;
  @output() afterCollapse!: any;
}
