// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatTree } from "@angular/material/tree";

/**
 * Wrapper for the CdkTable with Material design styles.
 */
@componentInterface({ selector: "mat-tree", acceptsChildren: true })
export class MatTreeComponentInterface {
}
