// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { MatSortHeaderIntl } from "@angular/material/sort";

/**
 * To modify the labels and text displayed, create a new instance of MatSortHeaderIntl and
include it in a custom provider.
 */
@externalType({ injectable: true })
export class MatSortHeaderIntlExternalType {}
