// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatSlider } from "@angular/material/slider";

/**
 * Allows users to select from a range of values by moving the slider thumb. It is similar in
behavior to the native `<input type="range">` element.
 */
@componentInterface({ selector: "mat-slider", acceptsChildren: true })
export class MatSliderComponentInterface {
  disabled!: any;
  discrete!: any;
  showTickMarks!: any;
  min!: any;
  color!: any;
  disableRipple!: any;
  max!: any;
  step!: any;
  displayWith!: any;
}
