// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { MatStartDate } from "@angular/material/datepicker";

/**
 * Input for entering the start date in a `mat-date-range-input`.
 */
@directiveInterface({ selector: "input[matStartDate]" })
export class MatStartDateDirectiveInterface {
  @output() dateChange!: any;
  @output() dateInput!: any;
}
