// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatSelectTrigger } from "@angular/material/select";

/**
 * Allows the user to customize the trigger that is displayed when the select has a value.
 */
@componentInterface({ selector: "mat-select-trigger" })
export class MatSelectTriggerComponentInterface {
}
