// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatGridTile } from "@angular/material/grid-list";

@componentInterface({ selector: "mat-grid-tile", acceptsChildren: true })
export class MatGridTileComponentInterface {
  rowspan!: any;
  colspan!: any;
}
