// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from '@apexdesigner/dsl/component-interface';
import { MatDatepickerToggle } from '@angular/material/datepicker';

/**
 * Mat Datepicker Toggle
 */
@componentInterface({ selector: 'mat-datepicker-toggle', acceptsChildren: true })
export class MatDatepickerToggleComponentInterface {
  for!: any;
  tabIndex!: any;
  'aria-label'!: any;
  disabled!: any;
  disableRipple!: any;
}
