// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class MatSortStartType extends BaseType<string> {}

applyValidValues(MatSortStartType, [
  "",
  "asc",
  "desc",
]);
