// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatMiniFabButton } from "@angular/material/button";

/**
 * Material Design mini floating action button (FAB) component. These buttons represent the primary
or most common action for users to interact with.
See https://material.io/components/buttons-floating-action-button/
 */
@directiveInterface({ selector: "button[mat-mini-fab]" })
export class MatMiniFabButtonDirectiveInterface {
}
