// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatDatepickerCancel } from "@angular/material/datepicker";

/**
 * Button that will close the datepicker and discard the current selection.
 */
@directiveInterface({ selector: "[matDateRangePickerCancel],[matDatepickerCancel]" })
export class MatDatepickerCancelDirectiveInterface {
}
