// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatGridTileText } from "@angular/material/grid-list";

@componentInterface({ selector: "mat-grid-tile-footer,mat-grid-tile-header", acceptsChildren: true })
export class MatGridTileTextComponentInterface {
}
