// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class MatProgressSpinnerModeType extends BaseType<string> {}

applyValidValues(MatProgressSpinnerModeType, [
  "determinate",
  "indeterminate",
]);
