// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class MatButtonToggleGroupAppearanceType extends BaseType<string> {}

applyValidValues(MatButtonToggleGroupAppearanceType, [
  "legacy",
  "standard",
]);
