// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatFooterCell } from "@angular/material/table";

/**
 * Footer cell template container that adds the right classes and role.
 */
@directiveInterface({ selector: "mat-footer-cell,td[mat-footer-cell]" })
export class MatFooterCellDirectiveInterface {
}
