// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatIcon } from "@angular/material/icon";

/**
 * Component to display an icon. It can be used in the following ways:

- Specify the svgIcon input to load an SVG icon from a URL previously registered with the
  addSvgIcon, addSvgIconInNamespace, addSvgIconSet, or addSvgIconSetInNamespace methods of
  MatIconRegistry. If the svgIcon value contains a colon it is assumed to be in the format
  "[namespace]:[name]", if not the value will be the name of an icon in the default namespace.
  Examples:
    `<mat-icon svgIcon="left-arrow"></mat-icon>
    <mat-icon svgIcon="animals:cat"></mat-icon>`

- Use a font ligature as an icon by putting the ligature text in the `fontIcon` attribute or the
  content of the `<mat-icon>` component. If you register a custom font class, don't forget to also
  include the special class `mat-ligature-font`. It is recommended to use the attribute alternative
  to prevent the ligature text to be selectable and to appear in search engine results.
  By default, the Material icons font is used as described at
  http://google.github.io/material-design-icons/#icon-font-for-the-web. You can specify an
  alternate font by setting the fontSet input to either the CSS class to apply to use the
  desired font, or to an alias previously registered with MatIconRegistry.registerFontClassAlias.
  Examples:
    `<mat-icon fontIcon="home"></mat-icon>
    <mat-icon>home</mat-icon>
    <mat-icon fontSet="myfont" fontIcon="sun"></mat-icon>
    <mat-icon fontSet="myfont">sun</mat-icon>`

- Specify a font glyph to be included via CSS rules by setting the fontSet input to specify the
  font, and the fontIcon input to specify the icon. Typically the fontIcon will specify a
  CSS class which causes the glyph to be displayed via a :before selector, as in
  https://fontawesome-v4.github.io/examples/
  Example:
    `<mat-icon fontSet="fa" fontIcon="alarm"></mat-icon>`
 */
@componentInterface({ selector: "mat-icon", acceptsChildren: true })
export class MatIconComponentInterface {
  color!: any;
  inline!: any;
  svgIcon!: any;
  fontSet!: any;
  fontIcon!: any;
}
