// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatActionList } from "@angular/material/list";

@componentInterface({ selector: "mat-action-list", acceptsChildren: true })
export class MatActionListComponentInterface {
}
