// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatNoDataRow } from "@angular/material/table";

/**
 * Row that can be used to display a message when no data is shown in the table.
 */
@directiveInterface({ selector: "ng-template[matNoDataRow]" })
export class MatNoDataRowDirectiveInterface {
}
