// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatSidenavContainer } from "@angular/material/sidenav";

@componentInterface({ selector: "mat-sidenav-container", acceptsChildren: true })
export class MatSidenavContainerComponentInterface {
}
