// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatSidenav } from "@angular/material/sidenav";

@componentInterface({ selector: "mat-sidenav", acceptsChildren: true })
export class MatSidenavComponentInterface {
  fixedInViewport!: any;
  fixedTopGap!: any;
  fixedBottomGap!: any;
}
