// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { MatDialogContent } from "@angular/material/dialog";

/**
 * Scrollable content container of a dialog.
 */
@componentInterface({ selector: "[mat-dialog-content],[matDialogContent],mat-dialog-content" })
export class MatDialogContentComponentInterface {
}
