// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MatProgressBar } from "@angular/material/progress-bar";

@componentInterface({ selector: "mat-progress-bar", acceptsChildren: true })
export class MatProgressBarComponentInterface {
  color!: any;
  value!: any;
  bufferValue!: any;
  mode!: any;
  @output() animationEnd!: any;
}
