// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { MatSort } from "@angular/material/sort";

/**
 * Container for MatSortables to manage the sort state and provide default sort parameters.
 */
@directiveInterface({ selector: "[matSort]" })
export class MatSortDirectiveInterface {
  matSortActive!: any;
  matSortStart!: any;
  matSortDirection!: any;
  matSortDisableClear!: any;
  matSortDisabled!: any;
  @output() matSortChange!: any;
}
