// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { MatAutocompleteOrigin } from "@angular/material/autocomplete";

/**
 * Directive applied to an element to make it usable
as a connection point for an autocomplete panel.
 */
@directiveInterface({ selector: "[matAutocompleteOrigin]" })
export class MatAutocompleteOriginDirectiveInterface {
}
