// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { MediaMatcher } from "@angular/cdk/layout";

/**
 * A utility for calling matchMedia queries.
 */
@externalType({ injectable: true })
export class MediaMatcherExternalType {}
