// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { MenuStack } from "@angular/cdk/menu";

/**
 * MenuStack allows subscribers to listen for close events (when a MenuStackItem is popped off
of the stack) in order to perform closing actions. Upon the MenuStack being empty it emits
from the `empty` observable specifying the next focus action which the listener should perform
as requested by the closer.
 */
@externalType({ injectable: true })
export class MenuStackExternalType {}
