// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MonacoFormFieldControl } from "@apexdesigner/schema-forms";

@componentInterface({ selector: "sf-monaco-control", acceptsChildren: true })
export class MonacoFormFieldControlComponentInterface {
  value!: any;
  placeholder!: any;
  required!: any;
  disabled!: any;
  @output() editorBlur!: any;
}
