// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { MonacoJsonFormFieldControl } from "@apexdesigner/schema-forms";

@componentInterface({ selector: "sf-monaco-json-control", acceptsChildren: true })
export class MonacoJsonFormFieldControlComponentInterface {
  value!: any;
  placeholder!: any;
  required!: any;
  disabled!: any;
  @output() editorBlur!: any;
}
