// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { NativeDateAdapter } from "@angular/material/core";

/**
 * Native Date Adapter
 *
 * Adapts the native JS Date for use with cdk-based components that work with dates.
 */
@externalType({ injectable: true, injectLocally: true })
export class NativeDateAdapterExternalType {}
