// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from '@apexdesigner/dsl/component-interface';

@componentInterface({ selector: 'ng-component', acceptsChildren: true })
export class NgComponentComponentInterface {}
