// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { NgComponentOutlet } from "@angular/common";

/**
 * Instantiates a {@link /api/core/Component Component} type and inserts its Host View into the current View.
`NgComponentOutlet` provides a declarative approach for dynamic component creation.

`NgComponentOutlet` requires a component type, if a falsy value is set the view will clear and
any existing component will be destroyed.
 */
@directiveInterface({ selector: "[ngComponentOutlet]" })
export class NgComponentOutletDirectiveInterface {
  ngComponentOutlet!: any;
  ngComponentOutletInputs!: any;
  ngComponentOutletInjector!: any;
  ngComponentOutletContent!: any;
  ngComponentOutletNgModule!: any;
  ngComponentOutletNgModuleFactory!: any;
}
