// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { NgForOf } from "@angular/common";

/**
 * A [structural directive](guide/directives/structural-directives) that renders
a template for each item in a collection.
The directive is placed on an element, which becomes the parent
of the cloned templates.

The `ngForOf` directive is generally used in the
[shorthand form](guide/directives/structural-directives#asterisk) `*ngFor`.
In this form, the template to be rendered for each iteration is the content
of an anchor element containing the directive.

The following example shows the shorthand syntax with some options,
contained in an `<li>` element.

```html
<li *ngFor="let item of items; index as i; trackBy: trackByFn">...</li>
```

The shorthand form expands into a long form that uses the `ngForOf` selector
on an `<ng-template>` element.
The content of the `<ng-template>` element is the `<li>` element that held the
short-form directive.

Here is the expanded version of the short-form example.

```html
<ng-template ngFor let-item [ngForOf]="items" let-i="index" [ngForTrackBy]="trackByFn">
  <li>...</li>
</ng-template>
```

Angular automatically expands the shorthand syntax as it compiles the template.
The context for each embedded view is logically merged to the current component
context according to its lexical position.

When using the shorthand syntax, Angular allows only [one structural directive
on an element](guide/directives/structural-directives#one-per-element).
If you want to iterate conditionally, for example,
put the `*ngIf` on a container element that wraps the `*ngFor` element.
For further discussion, see
[Structural Directives](guide/directives/structural-directives#one-per-element).
 */
@directiveInterface({ selector: "[ngFor][ngForOf]" })
export class NgForOfDirectiveInterface {
  ngForOf!: any;
  ngForTrackBy!: any;
  ngForTemplate!: any;
}
