// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { NgIf } from "@angular/common";

/**
 * A structural directive that conditionally includes a template based on the value of
an expression coerced to Boolean.
When the expression evaluates to true, Angular renders the template
provided in a `then` clause, and when  false or null,
Angular renders the template provided in an optional `else` clause. The default
template for the `else` clause is blank.

A [shorthand form](guide/directives/structural-directives#asterisk) of the directive,
`*ngIf="condition"`, is generally used, provided
as an attribute of the anchor element for the inserted template.
Angular expands this into a more explicit version, in which the anchor element
is contained in an `<ng-template>` element.

Simple form with shorthand syntax:

```html
<div *ngIf="condition">Content to render when condition is true.</div>
```

Simple form with expanded syntax:

```html
<ng-template [ngIf]="condition"><div>Content to render when condition is
true.</div></ng-template>
```

Form with an "else" block:

```html
<div *ngIf="condition; else elseBlock">Content to render when condition is true.</div>
<ng-template #elseBlock>Content to render when condition is false.</ng-template>
```

Shorthand form with "then" and "else" blocks:

```html
<div *ngIf="condition; then thenBlock else elseBlock"></div>
<ng-template #thenBlock>Content to render when condition is true.</ng-template>
<ng-template #elseBlock>Content to render when condition is false.</ng-template>
```

Form with storing the value locally:

```html
<div *ngIf="condition as value; else elseBlock">{{value}}</div>
<ng-template #elseBlock>Content to render when value is null.</ng-template>
```
 */
@directiveInterface({ selector: "[ngIf]" })
export class NgIfDirectiveInterface {
  ngIf!: any;
  ngIfThen!: any;
  ngIfElse!: any;
}
