// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { NgLocalization } from "@angular/common";

@externalType({ injectable: true })
export class NgLocalizationExternalType {}
