// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { FormsModule } from "@angular/forms";

@directiveInterface({ selector: "[ngModel]:not([formControlName]):not([formControl])" })
export class NgModelDirectiveInterface {
  name!: any;
  disabled!: any;
  ngModel!: any;
  ngModelOptions!: any;
  @output() ngModelChange!: any;
}
