// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { FormsModule } from "@angular/forms";

@directiveInterface({ selector: "[ngModelGroup]" })
export class NgModelGroupDirectiveInterface {
  ngModelGroup!: any;
}
