// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { NgOptimizedImage } from "@angular/common";

/**
 * Directive that improves image loading performance by enforcing best practices.

`NgOptimizedImage` ensures that the loading of the Largest Contentful Paint (LCP) image is
prioritized by:
- Automatically setting the `fetchpriority` attribute on the `<img>` tag
- Lazy loading non-priority images by default
- Automatically generating a preconnect link tag in the document head

In addition, the directive:
- Generates appropriate asset URLs if a corresponding `ImageLoader` function is provided
- Automatically generates a srcset
- Requires that `width` and `height` are set
- Warns if `width` or `height` have been set incorrectly
- Warns if the image will be visually distorted when rendered
 */
@directiveInterface({ selector: "img[ngSrc]" })
export class NgOptimizedImageDirectiveInterface {
  ngSrc!: any;
  ngSrcset!: any;
  sizes!: any;
  width!: any;
  height!: any;
  loading!: any;
  priority!: any;
  loaderParams!: any;
  disableOptimizedSrcset!: any;
  fill!: any;
  placeholder!: any;
  placeholderConfig!: any;
  src!: any;
  srcset!: any;
}
