// Generated by @apexdesigner/extract-interfaces
import { BaseType, applyValidValues } from "@apexdesigner/dsl";

export class NgOptimizedImageLoadingType extends BaseType<string> {}

applyValidValues(NgOptimizedImageLoadingType, [
  "lazy",
  "eager",
  "auto",
]);
