// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { NgPlural } from "@angular/common";

@directiveInterface({ selector: "[ngPlural]" })
export class NgPluralDirectiveInterface {
  ngPlural!: any;
}
