// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { NgPluralCase } from "@angular/common";

@directiveInterface({ selector: "[ngPluralCase]" })
export class NgPluralCaseDirectiveInterface {
}
