// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { NgStyle } from "@angular/common";

@directiveInterface({ selector: "[ngStyle]" })
export class NgStyleDirectiveInterface {
  ngStyle!: any;
}
