// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { NgSelectOption } from "@angular/forms";

@componentInterface({ selector: "option" })
export class NgSelectOptionComponentInterface {
  ngValue!: any;
  value!: any;
}
