// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { NgSwitchCase } from "@angular/common";

@directiveInterface({ selector: "[ngSwitchCase]" })
export class NgSwitchCaseDirectiveInterface {
  ngSwitchCase!: any;
}
