// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { NgSwitch } from "@angular/common";

@directiveInterface({ selector: "[ngSwitch]" })
export class NgSwitchDirectiveInterface {
  ngSwitch!: any;
}
