// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { NgTemplateOutlet } from "@angular/common";

@directiveInterface({ selector: "[ngTemplateOutlet]" })
export class NgTemplateOutletDirectiveInterface {
  ngTemplateOutletContext!: any;
  ngTemplateOutlet!: any;
  ngTemplateOutletInjector!: any;
}
