// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";

@componentInterface({ selector: "ng-template", acceptsChildren: true })
export class NgTemplateComponentInterface {
}
