// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { NgZone } from "@angular/core";

@externalType({ injectable: true })
export class NgZoneExternalType {}
