// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { OverlayContainer } from "@angular/cdk/overlay";

/**
 * Container inside which all overlays will render.
 */
@externalType({ injectable: true })
export class OverlayContainerExternalType {}
