// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { OverlayPositionBuilder } from "@angular/cdk/overlay";

/**
 * Overlay Position Builder
 *
 * Builder for overlay position strategy.
 */
@externalType({ injectable: true })
export class OverlayPositionBuilderExternalType {}
