// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { Overlay } from "@angular/cdk/overlay";

/**
 * Service to create Overlays. Overlays are dynamically added pieces of floating UI, meant to be
used as a low-level building block for other components. Dialogs, tooltips, menus,
selects, etc. can all be built using overlays. The service should primarily be used by authors
of re-usable components rather than developers building end-user applications.

An overlay *is* a PortalOutlet, so any kind of Portal can be loaded into one.
 */
@externalType({ injectable: true })
export class OverlayExternalType {}
