// Generated by @apexdesigner/extract-interfaces
import { pipeInterface } from "@apexdesigner/dsl/pipe-interface";
import { PercentPipe } from "@angular/common";

@pipeInterface({ selector: "percent" })
export class PercentPipePipeInterface {}
