// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { PlatformLocation } from "@angular/common";

/**
 * This class should not be used directly by an application developer. Instead, use
{@link Location}.

`PlatformLocation` encapsulates all calls to DOM APIs, which allows the Router to be
platform-agnostic.
This means that we can have different implementation of `PlatformLocation` for the different
platforms that Angular supports. For example, `@angular/platform-browser` provides an
implementation specific to the browser environment, while `@angular/platform-server` provides
one suitable for use with server-side rendering.

The `PlatformLocation` class is used directly by all implementations of {@link LocationStrategy}
when they need to interact with the DOM APIs like pushState, popState, etc.

{@link LocationStrategy} in turn is used by the {@link Location} service which is used directly
by the {@link /api/router/Router Router} in order to navigate between routes. Since all interactions between
{@link /api/router/Router Router} /
{@link Location} / {@link LocationStrategy} and DOM APIs flow through the `PlatformLocation`
class, they are all platform-agnostic.
 */
@externalType({ injectable: true })
export class PlatformLocationExternalType {}
