// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { Platform } from "@angular/cdk/platform";

/**
 * Service to detect the current platform by comparing the userAgent strings and
checking browser-specific global properties.
 */
@externalType({ injectable: true })
export class PlatformExternalType {}
