// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { Renderer2 } from "@angular/core";

@externalType({ injectable: true })
export class Renderer2ExternalType {}
