// Generated by @apexdesigner/extract-interfaces
import { externalType } from '@apexdesigner/dsl';
import { Router } from '@angular/router';

/**
 * Router
 *
 * @description
 *
 * A service that facilitates navigation among views and URL manipulation capabilities.
 * This service is provided in the root scope and configured with [provideRouter](api/router/provideRouter).
 *
 * @see {@link Route}
 * @see {@link provideRouter}
 * @see [Routing and Navigation Guide](guide/routing/common-router-tasks).
 *
 * @ngModule RouterModule
 *
 * @publicApi
 */
@externalType({ injectable: true })
export class RouterExternalType {}
