// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { Router } from "@angular/router";

@externalType({ injectable: true })
export class RouterExternalType {}
