// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { RouterLink } from "@angular/router";

@directiveInterface({ selector: "[routerLink]" })
export class RouterLinkDirectiveInterface {
  target!: any;
  queryParams!: any;
  fragment!: any;
  queryParamsHandling!: any;
  state!: any;
  info!: any;
  relativeTo!: any;
  preserveFragment!: any;
  skipLocationChange!: any;
  replaceUrl!: any;
  routerLink!: any;
}
