// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { RouteReuseStrategy } from "@angular/router";

@externalType({ injectable: true, injectLocally: true })
export class RouteReuseStrategyExternalType {}
