// Generated by @apexdesigner/extract-interfaces
import { directiveInterface, output } from "@apexdesigner/dsl/directive-interface";
import { RouterLinkActive } from "@angular/router";

@directiveInterface({ selector: "[routerLinkActive]" })
export class RouterLinkActiveDirectiveInterface {
  routerLinkActiveOptions!: any;
  ariaCurrentWhenActive!: any;
  routerLinkActive!: any;
  @output() isActiveChange!: any;
}
