// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { RouterOutlet } from "@angular/router";

@componentInterface({ selector: "router-outlet" })
export class RouterOutletComponentInterface {
  name!: any;
  routerOutletData!: any;
  @output() activate!: any;
  @output() deactivate!: any;
  @output() attach!: any;
  @output() detach!: any;
}
