// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { Sanitizer } from "@angular/core";

/**
 * Sanitizer is used by the views to sanitize potentially dangerous values.
 */
@externalType({ injectable: true })
export class SanitizerExternalType {}
