// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { SchemaFormCheckboxFieldComponent } from "@apexdesigner/schema-forms";

/**
 * A checkbox field that binds to a SchemaFormControl with a boolean schema type.
Displays the field's label next to the checkbox.
 */
@componentInterface({ selector: "sf-checkbox-field", acceptsChildren: true })
export class SchemaFormCheckboxFieldComponentComponentInterface {
  control!: any;
  label!: any;
  hideHelpText!: any;
}
