// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { SchemaFormSelectFieldComponent } from "@apexdesigner/schema-forms";

/**
 * A dropdown select field that binds to a SchemaFormControl.
Options are derived from the control's options property (enum or x-options in schema).
Supports clearing the selected value with a clear button.
 */
@componentInterface({ selector: "sf-select-field", acceptsChildren: true })
export class SchemaFormSelectFieldComponentComponentInterface {
  control!: any;
  label!: any;
  placeholder!: any;
  hideHelpText!: any;
  @output() enterPressed!: any;
}
