// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { SchemaFormJsonFieldComponent } from "@apexdesigner/schema-forms";

/**
 * JSON field component using mat-form-field with Monaco editor
 */
@componentInterface({ selector: "sf-json-field", acceptsChildren: true })
export class SchemaFormJsonFieldComponentComponentInterface {
  control!: any;
  placeholder!: any;
  label!: any;
  hideHelpText!: any;
  @output() enterPressed!: any;
}
