// Generated by @apexdesigner/extract-interfaces
import { componentInterface, output } from "@apexdesigner/dsl/component-interface";
import { SchemaFormFieldComponent } from "@apexdesigner/schema-forms";

/**
 * A dynamic field component that renders the appropriate field type based on the schema.
Uses SchemaFormsService to lazy-load field components based on the format metadata or inferred type.
This is the primary component for rendering individual form fields.
 */
@componentInterface({ selector: "sf-field", acceptsChildren: true })
export class SchemaFormFieldComponentComponentInterface {
  control!: any;
  placeholder!: any;
  label!: any;
  hideHelpText!: any;
  @output() linkClicked!: any;
  @output() enterPressed!: any;
}
