// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { SchemaFormDateTimeFieldComponent } from "@apexdesigner/schema-forms";

/**
 * A combined date and time picker field that binds to a SchemaFormControl.
Uses Luxon for date handling and stores values as ISO datetime strings.
Features an autocomplete for time selection with configurable minute steps.
 */
@componentInterface({ selector: "sf-datetime-field", acceptsChildren: true })
export class SchemaFormDateTimeFieldComponentComponentInterface {
  control!: any;
  placeholder!: any;
  hideHelpText!: any;
  label!: any;
  minDate!: any;
  maxDate!: any;
  minuteStep!: any;
}
