// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { ScrollStrategyOptions } from "@angular/cdk/overlay";

/**
 * Options for how an overlay will handle scrolling.

Users can provide a custom value for `ScrollStrategyOptions` to replace the default
behaviors. This class primarily acts as a factory for ScrollStrategy instances.
 */
@externalType({ injectable: true })
export class ScrollStrategyOptionsExternalType {}
