// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { ScrollDirective } from "@apexdesigner/flex-layout";

/**
 * A directive that enables vertical scrolling on an element.

Sets `overflow-y: auto` on the host element and adds `tabindex="0"` for keyboard
accessibility, allowing users to scroll the content using the keyboard.

Works well in combination with the `grow` directive to create scrollable content
areas within flex layouts.
 */
@directiveInterface({ selector: "[scroll]" })
export class ScrollDirectiveDirectiveInterface {
}
