// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { ShowOnDirtyErrorStateMatcher } from "@angular/material/core";

/**
 * Error state matcher that matches when a control is invalid and dirty.
 */
@externalType({ injectable: true })
export class ShowOnDirtyErrorStateMatcherExternalType {}
