// Generated by @apexdesigner/extract-interfaces
import { componentInterface } from "@apexdesigner/dsl/component-interface";
import { SimpleSnackBar } from "@angular/material/snack-bar";

@componentInterface({ selector: "simple-snack-bar", acceptsChildren: true })
export class SimpleSnackBarComponentInterface {
}
