// Generated by @apexdesigner/extract-interfaces
import { pipeInterface } from "@apexdesigner/dsl/pipe-interface";
import { SlicePipe } from "@angular/common";

@pipeInterface({ selector: "slice" })
export class SlicePipePipeInterface {}
