// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { TemplateRef } from "@angular/core";

@externalType({ injectable: true })
export class TemplateRefExternalType {}
