// Generated by @apexdesigner/extract-interfaces
import { directiveInterface } from "@apexdesigner/dsl/directive-interface";
import { TemplatePortalDirective } from "@angular/cdk/portal";

@directiveInterface({ selector: "[cdk-portal],[portal]" })
export class TemplatePortalDirectiveDirectiveInterface {
}
