// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { Title } from "@angular/platform-browser";

/**
 * A service that can be used to get and set the title of a current HTML document.

Since an Angular application can't be bootstrapped on the entire HTML document (`<html>` tag)
it is not possible to bind to the `text` property of the `HTMLTitleElement` elements
(representing the `<title>` tag). Instead, this service can be used to set and get the current
title value.
 */
@externalType({ injectable: true })
export class TitleExternalType {}
