// Generated by @apexdesigner/extract-interfaces
import { pipeInterface } from "@apexdesigner/dsl/pipe-interface";
import { TitleCasePipe } from "@angular/common";

/**
 * Transforms text to title case.
Capitalizes the first letter of each word and transforms the
rest of the word to lower case.
Words are delimited by any whitespace character, such as a space, tab, or line-feed character.
 */
@pipeInterface({ selector: "titlecase" })
export class TitleCasePipePipeInterface {}
