// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { TitleStrategy } from "@angular/router";

/**
 * Provides a strategy for setting the page title after a router navigation.

The built-in implementation traverses the router state snapshot and finds the deepest primary
outlet with `title` property. Given the `Routes` below, navigating to
`/base/child(popup:aux)` would result in the document title being set to "child".
```ts
[
  {path: 'base', title: 'base', children: [
    {path: 'child', title: 'child'},
  ],
  {path: 'aux', outlet: 'popup', title: 'popupTitle'}
]
```

This class can be used as a base class for custom title strategies. That is, you can create your
own class that extends the `TitleStrategy`. Note that in the above example, the `title`
from the named outlet is never used. However, a custom strategy might be implemented to
incorporate titles in named outlets.
 */
@externalType({ injectable: true })
export class TitleStrategyExternalType {}
