// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { UntypedFormBuilder } from "@angular/forms";

/**
 * UntypedFormBuilder is the same as `FormBuilder`, but it provides untyped controls.
 */
@externalType({ injectable: true })
export class UntypedFormBuilderExternalType {}
