// Generated by @apexdesigner/extract-interfaces
import { pipeInterface } from "@apexdesigner/dsl/pipe-interface";
import { UpperCasePipe } from "@angular/common";

/**
 * Transforms text to all upper case.
 */
@pipeInterface({ selector: "uppercase" })
export class UpperCasePipePipeInterface {}
