// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { UrlHandlingStrategy } from "@angular/router";

@externalType({ injectable: true })
export class UrlHandlingStrategyExternalType {}
