// Generated by @apexdesigner/extract-interfaces
import { externalType } from '@apexdesigner/dsl';
import { UrlHandlingStrategy } from '@angular/router';

@externalType({ injectable: true, injectLocally: true })
export class UrlHandlingStrategyExternalType {}
