// Generated by @apexdesigner/extract-interfaces
import { externalType } from "@apexdesigner/dsl";
import { ViewportScroller } from "@angular/common";

/**
 * Defines a scroll position manager. Implemented by `BrowserViewportScroller`.
 */
@externalType({ injectable: true })
export class ViewportScrollerExternalType {}
