// Generated by @apexdesigner/extract-interfaces
import { externalType } from '@apexdesigner/dsl';
import { ViewContainerRef } from '@angular/core';

/**
 * View Container Ref
 */
@externalType({ injectable: true })
export class ViewContainerRefExternalType {}
